# LIMPIEZA Y UNIFICACIÓN DE DATOS

El presente cuaderno limpia, estandariza y unifica los registros electorales históricos del partido Nuevo Liberalismo en Colombia. El cuaderno hace parte de un ejercicio exploratorio, analítico y prescriptivo, en el que, a través de la estadística,

Los datasets provienen de fuentes oficiales. Los registros electorales son descargados de manera individual en las páginas habilitadas por la Resgistraduría, en su mayoría como archivos ``.csv``, que son estandarizados, limpiados y unificados para su posterior uso en ejercicios analíticos como la realización de análisis estadístico exploratorio, (EDA), diseño de tableros de control, ejecución de consultas SQL (duckdb sin modelo relacional completo) y su uso para la prescripción de acciones y recomendaciones para la segmentación, fortalecimiento y mejora del rendimiento del partido de cara a futuras elecciones. 

Se toman como referencia dos periodos de relevancia: 

1) 1980-1988: Constituye el periodo inicial e histórico del partido. En este, el Nuevo Liberalismo se consolida de movimiento a partido político, obteniendo su primera personería jurídica hasta 1988, año en el que Luis Carlos Galán se reintegra al Partido Liberal y renuncia a la personería jurídica del partido. 

2) 2021-2026: Representa el periodo de renovación del partido, marcado por la devolución de la personería jurídica en el 2021.

## Bibliotecas

In [1]:
# Carga y manejo de archivos
from pathlib import Path
import os
import glob
import csv

# Procesamiento y limpieza de datos
import pandas as pd
import numpy as np
import re
from unidecode import unidecode

# Opcional: detección de encoding si algún CSV falla al leer
import chardet
from charset_normalizer import from_path

# Opcional: manejo de fechas
from datetime import datetime

# Opcional: warnings
import warnings
warnings.filterwarnings("ignore")

## Limpieza y unificación parcial

Se opta por un enfoque de limpieza de datos que prioriza la eficiencia y la claridad. Se utilizan bibliotecas estándar de Python como pandas y numpy para manipular los datos, mientras que se emplean expresiones regulares y la biblioteca unidecode para normalizar los textos. Además, se implementa un manejo cuidadoso de los archivos y directorios mediante pathlib y os, asegurando que el código sea robusto y fácil de mantener.

Además, se elige una limpieza de dos fases teniendo en cuenta la calidad y cantidad de archivos. Por ejemplo, los datos de elecciones como congreso 2026 y 2022 se hayan repartidos en varios archivos ``.csv`` o ``.xlsx``, separados por departamentos, lo cual añade pasos adicionales a su limpieza y unificación. Por ende, una vez unificados los archivos, se puede pasar a la construcción de la base de datos final.

### 1980-1988

In [2]:
from pathlib import Path
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

# Ruta de la carpeta del bloque 1980-1988
ruta_carpeta = Path(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\1980-1988")

# Buscar todos los archivos CSV
archivos_csv = sorted(ruta_carpeta.glob("*.csv"))

# Validación básica
if not archivos_csv:
    raise FileNotFoundError(f"No se encontraron archivos CSV en: {ruta_carpeta}")

# Cargar todos los archivos
dfs = []
dfs_por_nombre = {}

for archivo in archivos_csv:
    try:
        df_temp = pd.read_csv(archivo, low_memory=False, encoding="utf-8")
    except UnicodeDecodeError:
        try:
            df_temp = pd.read_csv(archivo, low_memory=False, encoding="latin-1")
        except UnicodeDecodeError:
            df_temp = pd.read_csv(archivo, low_memory=False, encoding="cp1252")

    # Agregar metadato útil
    df_temp["archivo_origen"] = archivo.name

    # Guardar en lista
    dfs.append(df_temp)

    # Guardar en diccionario con nombre limpio
    nombre_df = archivo.stem.lower().replace(" ", "_").replace("-", "_")
    dfs_por_nombre[nombre_df] = df_temp

# Confirmación
print(f"Archivos cargados: {len(dfs)}")
print("Nombres disponibles en dfs_por_nombre:")
for nombre in dfs_por_nombre.keys():
    print("-", nombre)

Archivos cargados: 16
Nombres disponibles en dfs_por_nombre:
- 1980_asamblea.dta
- 1980_concejo.dta
- 1982_asamblea.dta
- 1982_camara.dta
- 1982_concejo.dta
- 1982_presidencia.dta
- 1982_senado.dta
- 1984_asamblea.dta
- 1984_concejo.dta
- 1986_asamblea.dta
- 1986_camara.dta
- 1986_concejo.dta
- 1986_presidencia.dta
- 1986_senado.dta
- 1988_alcaldia.dta
- 1988_asamblea.dta

In [4]:
# Comparación de columnas entre dataframes
columnas_por_archivo = {
    nombre: set(df_temp.columns)
    for nombre, df_temp in dfs_por_nombre.items()
}

# Unión total de columnas
union_columnas = sorted(set().union(*columnas_por_archivo.values()))

# Columnas comunes a todos los archivos
columnas_comunes = sorted(set.intersection(*columnas_por_archivo.values()))

# Columnas exclusivas por archivo
columnas_exclusivas = {
    nombre: sorted(cols - set(columnas_comunes))
    for nombre, cols in columnas_por_archivo.items()
}

# Resumen por archivo
df_columnas = pd.DataFrame([
    {
        "archivo": nombre,
        "n_columnas": len(cols),
        "columnas_exclusivas": ", ".join(sorted(cols - set(columnas_comunes)))
    }
    for nombre, cols in columnas_por_archivo.items()
]).sort_values("archivo")

print("UNIÓN TOTAL DE COLUMNAS:")
print(union_columnas)

print("\nCOLUMNAS COMUNES A TODOS LOS ARCHIVOS:")
print(columnas_comunes)

print("\nRESUMEN POR ARCHIVO:")
print(df_columnas)

UNIÓN TOTAL DE COLUMNAS:
['ano', 'archivo_origen', 'circunscripcion', 'coddpto', 'coddpto80', 'coddpto82', 'coddpto84', 'coddpto86', 'coddpto88', 'codigo_lista', 'codigo_partido', 'codmpio', 'codmpio80', 'codmpio82', 'codmpio84', 'codmpio86', 'codmpio88', 'curules', 'departamento', 'departamento80', 'departamento82', 'departamento84', 'departamento86', 'departamento88', 'en_lista', 'fecha_eleccion', 'id_electoral', 'municipio', 'nombres', 'primer_apellido', 'segundo_apellido', 'tipo_eleccion', 'votos']

COLUMNAS COMUNES A TODOS LOS ARCHIVOS:
['ano', 'archivo_origen', 'circunscripcion', 'coddpto', 'codigo_lista', 'codigo_partido', 'codmpio', 'curules', 'departamento', 'fecha_eleccion', 'id_electoral', 'municipio', 'nombres', 'primer_apellido', 'segundo_apellido', 'tipo_eleccion', 'votos']

RESUMEN POR ARCHIVO:
                 archivo  n_columnas  \
0      1980_asamblea.dta          21
1       1980_concejo.dta          21
2      1982_asamblea.dta          21
3        1982_camara.dta          21
4       1982_concejo.dta          21
5   1982_presidencia.dta          20
6        1982_senado.dta          21
7      1984_asamblea.dta          21
8       1984_concejo.dta          20
9      1986_asamblea.dta          21
10       1986_camara.dta          21
11      1986_concejo.dta          21
12  1986_presidencia.dta          20
13       1986_senado.dta          21
14     1988_alcaldia.dta          20
15     1988_asamblea.dta          21

                               columnas_exclusivas
0   coddpto80, codmpio80, departamento80, en_lista
1   coddpto80, codmpio80, departamento80, en_lista
2   coddpto82, codmpio82, departamento82, en_lista
3   coddpto82, codmpio82, departamento82, en_lista
4   coddpto82, codmpio82, departamento82, en_lista
5             coddpto82, codmpio82, departamento82
6   coddpto82, codmpio82, departamento82, en_lista
7   coddpto84, codmpio84, departamento84, en_lista
8             coddpto84, codmpio84, departamento84
9   coddpto86, codmpio86, departamento86, en_lista
10  coddpto86, codmpio86, departamento86, en_lista
11  coddpto86, codmpio86, departamento86, en_lista
12            coddpto86, codmpio86, departamento86
13  coddpto86, codmpio86, departamento86, en_lista
14            coddpto88, codmpio88, departamento88
15  coddpto88, codmpio88, departamento88, en_lista

In [ ]:
import pandas as pd
from pathlib import Path

def estandarizar_columnas_segura(df):
    df = df.copy()

    renombres = {
        "coddpto80": "coddpto",
        "coddpto82": "coddpto",
        "coddpto84": "coddpto",
        "coddpto86": "coddpto",
        "coddpto88": "coddpto",
        "codmpio80": "codmpio",
        "codmpio82": "codmpio",
        "codmpio84": "codmpio",
        "codmpio86": "codmpio",
        "codmpio88": "codmpio",
        "departamento80": "departamento",
        "departamento82": "departamento",
        "departamento84": "departamento",
        "departamento86": "departamento",
        "departamento88": "departamento"
    }

    for col_old, col_new in renombres.items():
        if col_old in df.columns:
            if col_new in df.columns:
                df[col_new] = df[col_new].where(df[col_new].notna(), df[col_old])
                df = df.drop(columns=[col_old])
            else:
                df = df.rename(columns={col_old: col_new})

    if "en_lista" not in df.columns:
        df["en_lista"] = pd.NA

    return df

# Aplica esto sobre tu lista de dataframes ya cargada: dfs
dfs_limpios = [estandarizar_columnas_segura(df_temp) for df_temp in dfs]

# Concatenar
df_bloque_1980_1988 = pd.concat(dfs_limpios, ignore_index=True, sort=False)

# Normalizar nombres de columnas
df_bloque_1980_1988.columns = [c.lower() for c in df_bloque_1980_1988.columns]

# Exportar
output_dir = Path("output")
output_dir.mkdir(exist_ok=True)

csv_path = output_dir / "bloque_1980_1988_maestro.csv"
df_bloque_1980_1988.to_csv(csv_path, index=False, encoding="utf-8-sig")

print("Filas:", df_bloque_1980_1988.shape[0])
print("Columnas:", df_bloque_1980_1988.shape[1])
print("Archivo guardado en:", csv_path)

Filas: 534169
Columnas: 18
Archivo guardado en: output\bloque_1980_1988_maestro.csv

In [13]:
df_1980_1988 = pd.read_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\output\bloque_1980_1988_maestro.csv")
df_1980_1988.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534169 entries, 0 to 534168
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id_electoral      534169 non-null  int64
 1   ano               534169 non-null  int64
 2   tipo_eleccion     534169 non-null  object
 3   fecha_eleccion    534169 non-null  object
 4   coddpto           534169 non-null  float64
 5   departamento      534151 non-null  object
 6   codmpio           534169 non-null  float64
 7   municipio         534067 non-null  object
 8   circunscripcion   534169 non-null  object
 9   codigo_partido    502402 non-null  float64
 10  codigo_lista      534169 non-null  int64
 11  en_lista          248999 non-null  float64
 12  primer_apellido   291646 non-null  object
 13  segundo_apellido  243537 non-null  object
 14  nombres           501992 non-null  object
 15  votos             534166 non-null  float64
 16  curules           492894 non-null  float64
 17  archivo_origen    534169 non-null  object
dtypes: float64(6), int64(3), object(9)
memory usage: 73.4+ MB

In [14]:
import pandas as pd
import unicodedata

def quitar_tildes(x):
    if pd.isna(x):
        return x
    x = str(x)
    x = unicodedata.normalize("NFKD", x)
    return "".join(c for c in x if not unicodedata.combining(c))

# 1) Eliminar fecha_eleccion
df_1980_1988 = df_1980_1988.drop(columns=["fecha_eleccion","codigo_lista","en_lista","curules","archivo_origen"], errors="ignore")

# 2) Homogeneizar texto y quitar tildes
text_cols = df_1980_1988.select_dtypes(include=["object", "string"]).columns
df_1980_1988[text_cols] = (
    df_1980_1988[text_cols]
    .astype("string")
    .apply(lambda col: col.str.strip().str.lower().map(quitar_tildes))
    .fillna("sin_dato")
)

# 3) Ajustar dtypes numéricos
df_1980_1988[["id_electoral", "ano", "coddpto", "codmpio", "codigo_partido"]] = (
    df_1980_1988[["id_electoral", "ano", "coddpto", "codmpio", "codigo_partido"]]
    .astype("Int64")
)

# 4) Votos como entero nullable
df_1980_1988["votos"] = pd.to_numeric(df_1980_1988["votos"], errors="coerce").round().astype("Int64")

# 5) Revisión
df_1980_1988.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534169 entries, 0 to 534168
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id_electoral      534169 non-null  Int64
 1   ano               534169 non-null  Int64
 2   tipo_eleccion     534169 non-null  object
 3   coddpto           534169 non-null  Int64
 4   departamento      534169 non-null  object
 5   codmpio           534169 non-null  Int64
 6   municipio         534169 non-null  object
 7   circunscripcion   534169 non-null  object
 8   codigo_partido    502402 non-null  Int64
 9   primer_apellido   534169 non-null  object
 10  segundo_apellido  534169 non-null  object
 11  nombres           534169 non-null  object
 12  votos             534166 non-null  Int64
dtypes: Int64(6), object(7)
memory usage: 56.0+ MB

In [21]:
df_1980_1988["nombre_completo"] = (
    df_1980_1988["nombres"].fillna("sin_dato").str.strip() + " " +
    df_1980_1988["primer_apellido"].fillna("sin_dato").str.strip() + " " +
    df_1980_1988["segundo_apellido"].fillna("sin_dato").str.strip()
).str.replace(r"\s+", " ", regex=True).str.strip()

In [31]:
reemplazos = {
    "movimiento nuevo liberalismo sin_dato sin_dato": "movimiento nuevo liberalismo",
    "luis carlos galan sin_dato": "luis carlos galan sarmiento",
    "jorge eliecer maldonado sin_dato": "jorge eliecer maldonado",
    "cecilia castro sin_dato": "cecilia castro",
    "herman lozano sin_dato": "herman lozano",
    "pedro julio sanchez sin_dato": "pedro julio sanchez",
    "partido nuevo liberalismo sin_dato sin_dato": "partido nuevo liberalismo",
    "movimiento de izquierda nuevo liberal 82 sin_dato sin_dato": "movimiento de izquierda nuevo liberal 82"
}

df_1980_1988["nombre_completo"] = df_1980_1988["nombre_completo"].replace(reemplazos)

In [46]:
import duckdb

query_sql = """
SELECT *
FROM 
    df_1980_1988
WHERE
    codigo_partido = '19790001'
    OR nombres IN ('movimiento nuevo liberalismo', 'movimiento de izquierda nuevo liberal 82','partido nuevo liberalismo')

"""

# Ejecutar la consulta y convertir el resultado a un nuevo DataFrame
df_88_sql = duckdb.sql(query_sql).df()
df_88_sql.head(100)

,id_electoral,ano,tipo_eleccion,coddpto,departamento,codmpio,municipio,circunscripcion,codigo_partido,primer_apellido,segundo_apellido,nombres,votos,nombre_completo
0,319820007,1982,camara de representantes,19,cauca,19001,popayan,departamental,19790001,sin_dato,sin_dato,movimiento de izquierda nuevo liberal 82,1411,movimiento de izquierda nuevo liberal 82
1,319820007,1982,camara de representantes,19,cauca,19001,popayan,departamental,19790001,velasco,ramirez,omar henry,0,omar henry velasco ramirez
2,319820007,1982,camara de representantes,19,cauca,19022,almaguer,departamental,19790001,sin_dato,sin_dato,movimiento de izquierda nuevo liberal 82,5,movimiento de izquierda nuevo liberal 82
3,319820007,1982,camara de representantes,19,cauca,19022,almaguer,departamental,19790001,velasco,ramirez,omar henry,0,omar henry velasco ramirez
4,319820007,1982,camara de representantes,19,cauca,19050,argelia,departamental,19790001,sin_dato,sin_dato,movimiento de izquierda nuevo liberal 82,108,movimiento de izquierda nuevo liberal 82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,319820015,1982,camara de representantes,50,meta,50568,puerto gaitan,departamental,19790001,lopez,bejarano,jesus,0,jesus lopez bejarano
96,319820015,1982,camara de representantes,50,meta,50573,puerto lopez,departamental,19790001,sin_dato,sin_dato,movimiento de izquierda nuevo liberal 82,243,movimiento de izquierda nuevo liberal 82
97,319820015,1982,camara de representantes,50,meta,50573,puerto lopez,departamental,19790001,lopez,bejarano,jesus,0,jesus lopez bejarano
98,319820015,1982,camara de representantes,50,meta,50577,puerto lleras,departamental,19790001,sin_dato,sin_dato,movimiento de izquierda nuevo liberal 82,342,movimiento de izquierda nuevo liberal 82
99,319820015,1982,camara de representantes,50,meta,50577,puerto lleras,departamental,19790001,lopez,bejarano,jesus,0,jesus lopez bejarano

In [47]:
df_88_sql.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14142 entries, 0 to 14141
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_electoral      14142 non-null  int64
 1   ano               14142 non-null  int64
 2   tipo_eleccion     14142 non-null  object
 3   coddpto           14142 non-null  int64
 4   departamento      14142 non-null  object
 5   codmpio           14142 non-null  int64
 6   municipio         14142 non-null  object
 7   circunscripcion   14142 non-null  object
 8   codigo_partido    14142 non-null  int64
 9   primer_apellido   14142 non-null  object
 10  segundo_apellido  14142 non-null  object
 11  nombres           14142 non-null  object
 12  votos             14142 non-null  int64
 13  nombre_completo   14142 non-null  object
dtypes: int64(6), object(8)
memory usage: 1.5+ MB

In [40]:
df_1980_1988.to_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\output\80_88_limpio.csv", index=False, encoding="utf-8-sig")

In [48]:
df_88_sql.to_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\output\80_88_nuevo_liberalismo.csv", index=False, encoding="utf-8-sig")

### 2021-2026

#### 2026/congreso

In [2]:
from pathlib import Path
import pandas as pd

carpeta = Path(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\2021-actualidad\2026")
salida = carpeta / "parciales"
salida.mkdir(exist_ok=True)

archivos = sorted(carpeta.glob("*.xlsx"))

for i, archivo in enumerate(archivos, 1):
    print(f"[{i}/{len(archivos)}] Leyendo: {archivo.name}")
    try:
        df = pd.read_excel(archivo)
        df.to_csv(salida / f"{archivo.stem}.csv", index=False, encoding="utf-8-sig")
        print(f"    OK -> {archivo.stem}.csv")
    except Exception as e:
        print(f"    ERROR -> {archivo.name}: {e}")

parciales = sorted(salida.glob("*.csv"))
df_congreso_2026 = pd.concat(
    [pd.read_csv(archivo, encoding="utf-8-sig") for archivo in parciales],
    ignore_index=True
)

[1/51] Leyendo: amazonas.xlsx
    OK -> amazonas.csv
[2/51] Leyendo: antioquia.xlsx
    OK -> antioquia.csv
[3/51] Leyendo: MMV_XXX_01_000_XXX_XX_XX_XXX_1036.csv.xlsx
    OK -> MMV_XXX_01_000_XXX_XX_XX_XXX_1036.csv.csv
[4/51] Leyendo: MMV_XXX_01_000_XXX_XX_XX_XXX_1039.csv.xlsx
    OK -> MMV_XXX_01_000_XXX_XX_XX_XXX_1039.csv.csv
[5/51] Leyendo: MMV_XXX_01_000_XXX_XX_XX_XXX_1046.csv.xlsx
    OK -> MMV_XXX_01_000_XXX_XX_XX_XXX_1046.csv.csv
[6/51] Leyendo: MMV_XXX_01_000_XXX_XX_XX_XXX_1049.csv.xlsx
    OK -> MMV_XXX_01_000_XXX_XX_XX_XXX_1049.csv.csv
[7/51] Leyendo: MMV_XXX_03_000_XXX_XX_XX_XXX_1001.csv.xlsx
    OK -> MMV_XXX_03_000_XXX_XX_XX_XXX_1001.csv.csv
[8/51] Leyendo: MMV_XXX_05_000_XXX_XX_XX_XXX_1002.csv.xlsx
    OK -> MMV_XXX_05_000_XXX_XX_XX_XXX_1002.csv.csv
[9/51] Leyendo: MMV_XXX_05_000_XXX_XX_XX_XXX_1041.csv.xlsx
    OK -> MMV_XXX_05_000_XXX_XX_XX_XXX_1041.csv.csv
[10/51] Leyendo: MMV_XXX_07_000_XXX_XX_XX_XXX_1003.csv.xlsx
    OK -> MMV_XXX_07_000_XXX_XX_XX_XXX_1003.csv.csv
[11/51] Leyendo: MMV_XXX_09_000_XXX_XX_XX_XXX_1004.csv.xlsx
    OK -> MMV_XXX_09_000_XXX_XX_XX_XXX_1004.csv.csv
[12/51] Leyendo: MMV_XXX_11_000_XXX_XX_XX_XXX_1005.csv.xlsx
    OK -> MMV_XXX_11_000_XXX_XX_XX_XXX_1005.csv.csv
[13/51] Leyendo: MMV_XXX_11_000_XXX_XX_XX_XXX_1034.csv.xlsx
    OK -> MMV_XXX_11_000_XXX_XX_XX_XXX_1034.csv.csv
[14/51] Leyendo: MMV_XXX_11_000_XXX_XX_XX_XXX_1042.csv.xlsx
    OK -> MMV_XXX_11_000_XXX_XX_XX_XXX_1042.csv.csv
[15/51] Leyendo: MMV_XXX_12_000_XXX_XX_XX_XXX_1006.csv.xlsx
    OK -> MMV_XXX_12_000_XXX_XX_XX_XXX_1006.csv.csv
[16/51] Leyendo: MMV_XXX_12_000_XXX_XX_XX_XXX_1045.csv.xlsx
    OK -> MMV_XXX_12_000_XXX_XX_XX_XXX_1045.csv.csv
[17/51] Leyendo: MMV_XXX_13_000_XXX_XX_XX_XXX_1007.csv.xlsx
    OK -> MMV_XXX_13_000_XXX_XX_XX_XXX_1007.csv.csv
[18/51] Leyendo: MMV_XXX_13_000_XXX_XX_XX_XXX_1047.csv.xlsx
    OK -> MMV_XXX_13_000_XXX_XX_XX_XXX_1047.csv.csv
[19/51] Leyendo: MMV_XXX_15_000_XXX_XX_XX_XXX_1008.csv.xlsx
    OK -> MMV_XXX_15_000_XXX_XX_XX_XXX_1008.csv.csv
[20/51] Leyendo: MMV_XXX_16_000_XXX_XX_XX_XXX_1009.csv.xlsx
    OK -> MMV_XXX_16_000_XXX_XX_XX_XXX_1009.csv.csv
[21/51] Leyendo: MMV_XXX_17_000_XXX_XX_XX_XXX_1010.csv.xlsx
    OK -> MMV_XXX_17_000_XXX_XX_XX_XXX_1010.csv.csv
[22/51] Leyendo: MMV_XXX_19_000_XXX_XX_XX_XXX_1011.csv.xlsx
    OK -> MMV_XXX_19_000_XXX_XX_XX_XXX_1011.csv.csv
[23/51] Leyendo: MMV_XXX_19_000_XXX_XX_XX_XXX_1038.csv.xlsx
    OK -> MMV_XXX_19_000_XXX_XX_XX_XXX_1038.csv.csv
[24/51] Leyendo: MMV_XXX_21_000_XXX_XX_XX_XXX_1012.csv.xlsx
    OK -> MMV_XXX_21_000_XXX_XX_XX_XXX_1012.csv.csv
[25/51] Leyendo: MMV_XXX_23_000_XXX_XX_XX_XXX_1013.csv.xlsx
    OK -> MMV_XXX_23_000_XXX_XX_XX_XXX_1013.csv.csv
[26/51] Leyendo: MMV_XXX_23_000_XXX_XX_XX_XXX_1043.csv.xlsx
    OK -> MMV_XXX_23_000_XXX_XX_XX_XXX_1043.csv.csv
[27/51] Leyendo: MMV_XXX_24_000_XXX_XX_XX_XXX_1014.csv.xlsx
    OK -> MMV_XXX_24_000_XXX_XX_XX_XXX_1014.csv.csv
[28/51] Leyendo: MMV_XXX_25_000_XXX_XX_XX_XXX_1015.csv.xlsx
    OK -> MMV_XXX_25_000_XXX_XX_XX_XXX_1015.csv.csv
[29/51] Leyendo: MMV_XXX_25_000_XXX_XX_XX_XXX_1037.csv.xlsx
    OK -> MMV_XXX_25_000_XXX_XX_XX_XXX_1037.csv.csv
[30/51] Leyendo: MMV_XXX_26_000_XXX_XX_XX_XXX_1016.csv.xlsx
    OK -> MMV_XXX_26_000_XXX_XX_XX_XXX_1016.csv.csv
[31/51] Leyendo: MMV_XXX_27_000_XXX_XX_XX_XXX_1017.csv.xlsx
    OK -> MMV_XXX_27_000_XXX_XX_XX_XXX_1017.csv.csv
[32/51] Leyendo: MMV_XXX_28_000_XXX_XX_XX_XXX_1018.csv.xlsx
    OK -> MMV_XXX_28_000_XXX_XX_XX_XXX_1018.csv.csv
[33/51] Leyendo: MMV_XXX_29_000_XXX_XX_XX_XXX_1019.csv.xlsx
    OK -> MMV_XXX_29_000_XXX_XX_XX_XXX_1019.csv.csv
[34/51] Leyendo: MMV_XXX_29_000_XXX_XX_XX_XXX_1048.csv.xlsx
    OK -> MMV_XXX_29_000_XXX_XX_XX_XXX_1048.csv.csv
[35/51] Leyendo: MMV_XXX_31_000_XXX_XX_XX_XXX_1020.csv.xlsx
    OK -> MMV_XXX_31_000_XXX_XX_XX_XXX_1020.csv.csv
[36/51] Leyendo: MMV_XXX_40_000_XXX_XX_XX_XXX_1021.csv.xlsx
    OK -> MMV_XXX_40_000_XXX_XX_XX_XXX_1021.csv.csv
[37/51] Leyendo: MMV_XXX_40_000_XXX_XX_XX_XXX_1035.csv.xlsx
    OK -> MMV_XXX_40_000_XXX_XX_XX_XXX_1035.csv.csv
[38/51] Leyendo: MMV_XXX_44_000_XXX_XX_XX_XXX_1022.csv.xlsx
    OK -> MMV_XXX_44_000_XXX_XX_XX_XXX_1022.csv.csv
[39/51] Leyendo: MMV_XXX_46_000_XXX_XX_XX_XXX_1023.csv.xlsx
    OK -> MMV_XXX_46_000_XXX_XX_XX_XXX_1023.csv.csv
[40/51] Leyendo: MMV_XXX_48_000_XXX_XX_XX_XXX_1024.csv.xlsx
    OK -> MMV_XXX_48_000_XXX_XX_XX_XXX_1024.csv.csv
[41/51] Leyendo: MMV_XXX_50_000_XXX_XX_XX_XXX_1025.csv.xlsx
    OK -> MMV_XXX_50_000_XXX_XX_XX_XXX_1025.csv.csv
[42/51] Leyendo: MMV_XXX_52_000_XXX_XX_XX_XXX_1026.csv.xlsx
    OK -> MMV_XXX_52_000_XXX_XX_XX_XXX_1026.csv.csv
[43/51] Leyendo: MMV_XXX_52_000_XXX_XX_XX_XXX_1040.csv.xlsx
    OK -> MMV_XXX_52_000_XXX_XX_XX_XXX_1040.csv.csv
[44/51] Leyendo: MMV_XXX_54_000_XXX_XX_XX_XXX_1027.csv.xlsx
    OK -> MMV_XXX_54_000_XXX_XX_XX_XXX_1027.csv.csv
[45/51] Leyendo: MMV_XXX_56_000_XXX_XX_XX_XXX_1028.csv.xlsx
    OK -> MMV_XXX_56_000_XXX_XX_XX_XXX_1028.csv.csv
[46/51] Leyendo: MMV_XXX_64_000_XXX_XX_XX_XXX_1030.csv.xlsx
    OK -> MMV_XXX_64_000_XXX_XX_XX_XXX_1030.csv.csv
[47/51] Leyendo: MMV_XXX_64_000_XXX_XX_XX_XXX_1044.csv.xlsx
    OK -> MMV_XXX_64_000_XXX_XX_XX_XXX_1044.csv.csv
[48/51] Leyendo: MMV_XXX_68_000_XXX_XX_XX_XXX_1031.csv.xlsx
    OK -> MMV_XXX_68_000_XXX_XX_XX_XXX_1031.csv.csv
[49/51] Leyendo: MMV_XXX_72_000_XXX_XX_XX_XXX_1032.csv.xlsx
    OK -> MMV_XXX_72_000_XXX_XX_XX_XXX_1032.csv.csv
[50/51] Leyendo: MMV_XXX_88_000_XXX_XX_XX_XXX_1033.csv.xlsx
    OK -> MMV_XXX_88_000_XXX_XX_XX_XXX_1033.csv.csv
[51/51] Leyendo: MMV_XXX_88_000_XXX_XX_XX_XXX_1050.csv.xlsx
    OK -> MMV_XXX_88_000_XXX_XX_XX_XXX_1050.csv.csv

In [4]:
df_congreso_2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15242312 entries, 0 to 15242311
Data columns (total 19 columns):
 #   Column      Dtype
---  ------      -----
 0   DEP         int64
 1   DEPNOMBRE   object
 2   MUN         int64
 3   MUNNOMBRE   object
 4   ZONA        int64
 5   PUESTO      object
 6   PUESNOMBRE  object
 7   MESA        int64
 8   COMUCODIGO  int64
 9   COMUNOMBRE  object
 10  CORCODIGO   int64
 11  CORNOMBRE   object
 12  CIR         int64
 13  PAR         int64
 14  PARNOMBRE   object
 15  CAN         int64
 16  CANCEDULA   float64
 17  CANNOMBRE   object
 18  VOTOS       int64
dtypes: float64(1), int64(10), object(8)
memory usage: 2.2+ GB

In [6]:
df_congreso_2026["PUESTO"] = df_congreso_2026["PUESTO"].astype("string")

df_congreso_2026.to_parquet(
    salida / "df_congreso_2026.parquet",
    index=False
)

In [7]:
salida = Path(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\2021-actualidad")
salida.mkdir(exist_ok=True)

df_congreso_2026.to_csv(
    salida / "df_congreso_2026.csv.gz",
    index=False,
    encoding="utf-8-sig",
    compression="gzip"
)

In [13]:
import duckdb

query = """
SELECT *
FROM 
    df_congreso_2026
WHERE CANNOMBRE = 'JUAN MANUEL GALAN PACHON'
    OR PARNOMBRE LIKE '%NUEVO LIBERALISMO%'
"""

# Ejecutar la consulta y convertir el resultado a un nuevo DataFrame
df_26_sql = duckdb.sql(query).df()
df_26_sql.head(100)

,DEP,DEPNOMBRE,MUN,MUNNOMBRE,ZONA,PUESTO,PUESNOMBRE,MESA,COMUCODIGO,COMUNOMBRE,CORCODIGO,CORNOMBRE,CIR,PAR,PARNOMBRE,CAN,CANCEDULA,CANNOMBRE,VOTOS
0,60,AMAZONAS,1,LETICIA,98,1,CARCEL,1,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,3
1,60,AMAZONAS,1,LETICIA,99,77,KILOMETRO 11,1,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,2
2,60,AMAZONAS,1,LETICIA,99,76,IE SAN JUAN BOSCO,1,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,5
3,60,AMAZONAS,1,LETICIA,2,3,IE SAGRADO CORAZON DE JESUS,1,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,3
4,60,AMAZONAS,1,LETICIA,2,3,IE SAGRADO CORAZON DE JESUS,2,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,60,AMAZONAS,1,LETICIA,1,2,JORGE ELIECER GAITAN,8,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,1
96,60,AMAZONAS,1,LETICIA,1,2,JORGE ELIECER GAITAN,9,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,1
97,60,AMAZONAS,1,LETICIA,1,2,JORGE ELIECER GAITAN,10,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,2
98,60,AMAZONAS,1,LETICIA,1,2,JORGE ELIECER GAITAN,11,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,3
99,60,AMAZONAS,1,LETICIA,1,2,JORGE ELIECER GAITAN,12,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,2

In [17]:
df_26_sql.to_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\output\26_congreso_nuevo_liberalismo.csv", index=False, encoding="utf-8-sig")

#### 2023/territoriales

In [19]:
df_territoriales_2023 = pd.read_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\2021-actualidad\MMV_2023_NACIONAL.csv")
df_territoriales_2023.head()

,Código Departamento,Nombre Departamento,Código Municipio,Nombre Municipio,Código Zona,Código Puesto,Nombre Puesto,Mesa,Código Comuna,Nombre Comuna,Código Corporación,Nombre Corporación,Código Circunscripción,Código Partido,Nombre Partido,Código Candidato,Nombre Candidato,Total Votos
0,1,ANTIOQUIA,1,MEDELLIN,1,1,SEC. ESC. LA ESPERANZA NO 2,1,1,COMUNA 1 POPULAR,1,GOBERNADOR,1,0,CANDIDATOS TOTALES,997,VOTOS NULOS,5
1,1,ANTIOQUIA,1,MEDELLIN,1,1,SEC. ESC. LA ESPERANZA NO 2,1,1,COMUNA 1 POPULAR,1,GOBERNADOR,1,0,CANDIDATOS TOTALES,996,VOTOS EN BLANCO,2
2,1,ANTIOQUIA,1,MEDELLIN,1,1,SEC. ESC. LA ESPERANZA NO 2,1,1,COMUNA 1 POPULAR,1,GOBERNADOR,1,0,CANDIDATOS TOTALES,998,VOTOS NO MARCADOS,30
3,1,ANTIOQUIA,1,MEDELLIN,1,1,SEC. ESC. LA ESPERANZA NO 2,1,1,COMUNA 1 POPULAR,1,GOBERNADOR,1,2,PARTIDO CONSERVADOR COLOMBIANO,9,JUAN DIEGO GOMEZ JIMENEZ,2
4,1,ANTIOQUIA,1,MEDELLIN,1,1,SEC. ESC. LA ESPERANZA NO 2,1,1,COMUNA 1 POPULAR,1,GOBERNADOR,1,24,PARTIDO DEMÓCRATA COLOMBIANO,2,JULIAN BEDOYA PULGARIN,1

In [23]:
query = """
SELECT *
FROM 
    df_territoriales_2023
WHERE "Nombre Partido" LIKE '%NUEVO LIBERALISMO%'
"""

# Ejecutar la consulta y convertir el resultado a un nuevo DataFrame
df_23_sql = duckdb.sql(query).df()
df_23_sql.head(100)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,Código Departamento,Nombre Departamento,Código Municipio,Nombre Municipio,Código Zona,Código Puesto,Nombre Puesto,Mesa,Código Comuna,Nombre Comuna,Código Corporación,Nombre Corporación,Código Circunscripción,Código Partido,Nombre Partido,Código Candidato,Nombre Candidato,Total Votos
0,1,ANTIOQUIA,1,MEDELLIN,7,1,COL AGUSTINIANO DE SAN NICOLAS,1,4,COMUNA 4 ARANJUEZ,5,JAL,3,19,PARTIDO NUEVO LIBERALISMO,82,PAOLA STEFANIA GUISAO URREGO,1
1,1,ANTIOQUIA,1,MEDELLIN,7,1,COL AGUSTINIANO DE SAN NICOLAS,10,4,COMUNA 4 ARANJUEZ,5,JAL,3,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
2,1,ANTIOQUIA,1,MEDELLIN,7,1,COL AGUSTINIANO DE SAN NICOLAS,11,4,COMUNA 4 ARANJUEZ,5,JAL,3,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,2
3,1,ANTIOQUIA,1,MEDELLIN,7,1,COL AGUSTINIANO DE SAN NICOLAS,11,4,COMUNA 4 ARANJUEZ,5,JAL,3,19,PARTIDO NUEVO LIBERALISMO,81,JONATHAN ANDRES ALVAREZ MACHADO,2
4,1,ANTIOQUIA,1,MEDELLIN,7,1,COL AGUSTINIANO DE SAN NICOLAS,13,4,COMUNA 4 ARANJUEZ,5,JAL,3,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,ANTIOQUIA,1,MEDELLIN,7,3,I.E. GILBERTO ALZATE AVENDAÑO,10,4,COMUNA 4 ARANJUEZ,5,JAL,3,19,PARTIDO NUEVO LIBERALISMO,82,PAOLA STEFANIA GUISAO URREGO,1
96,1,ANTIOQUIA,1,MEDELLIN,7,3,I.E. GILBERTO ALZATE AVENDAÑO,12,4,COMUNA 4 ARANJUEZ,5,JAL,3,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
97,1,ANTIOQUIA,1,MEDELLIN,7,3,I.E. GILBERTO ALZATE AVENDAÑO,12,4,COMUNA 4 ARANJUEZ,5,JAL,3,19,PARTIDO NUEVO LIBERALISMO,81,JONATHAN ANDRES ALVAREZ MACHADO,1
98,1,ANTIOQUIA,1,MEDELLIN,7,3,I.E. GILBERTO ALZATE AVENDAÑO,12,4,COMUNA 4 ARANJUEZ,5,JAL,3,19,PARTIDO NUEVO LIBERALISMO,82,PAOLA STEFANIA GUISAO URREGO,1
99,1,ANTIOQUIA,1,MEDELLIN,7,3,I.E. GILBERTO ALZATE AVENDAÑO,13,4,COMUNA 4 ARANJUEZ,5,JAL,3,19,PARTIDO NUEVO LIBERALISMO,82,PAOLA STEFANIA GUISAO URREGO,1

In [24]:
df_23_sql.to_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\output\23_territoriales_nuevo_liberalismo.csv", index=False, encoding="utf-8-sig")

#### 2022/congreso

In [29]:
import pandas as pd
from pathlib import Path

carpeta = Path(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\2021-actualidad\2022")
archivos = sorted(carpeta.glob("MMV_2022_*.csv"))

encodings = ["utf-16-le", "utf-8", "cp1252", "latin1"]
separador = ","

dfs = []

for archivo in archivos:
    df = None
    for enc in encodings:
        try:
            df = pd.read_csv(
                archivo,
                encoding=enc,
                sep=separador,
                engine="python",
                on_bad_lines="skip"
            )
            print(f"{archivo.name} -> {enc}, {df.shape}")
            break
        except Exception as e:
            print(f"{archivo.name} falló con {enc}: {type(e).__name__}")
            continue
    if df is not None:
        dfs.append(df)
    else:
        print(f"{archivo.name} no se pudo leer con ninguna codificación")

df_congreso_2022 = pd.concat(dfs, ignore_index=True) if dfs else None
if df_congreso_2022 is not None:
    print("Shape final:", df_congreso_2022.shape)
    print("Columnas:", df_congreso_2022.columns.tolist())

MMV_2022_01_ANTIOQUIA.csv -> utf-16-le, (1346671, 21)
MMV_2022_03_ATLANTICO.csv -> utf-16-le, (498184, 21)
MMV_2022_05_BOLIVAR.csv -> utf-16-le, (363811, 21)
MMV_2022_07_BOYACA.csv -> utf-16-le, (258451, 21)
MMV_2022_09_CALDAS.csv -> utf-16-le, (199349, 21)
MMV_2022_11_CAUCA.csv -> utf-16-le, (191014, 21)
MMV_2022_12_CESAR.csv -> utf-16-le, (186559, 21)
MMV_2022_13_CORDOBA.csv -> utf-16-le, (227727, 21)
MMV_2022_15_CUNDINAMARCA.csv -> utf-16-le, (554780, 21)
MMV_2022_16_BOGOTA.csv -> utf-16-le, (1759916, 21)
MMV_2022_17_CHOCO.csv -> utf-16-le, (59529, 21)
MMV_2022_19_HUILA.csv -> utf-16-le, (192198, 21)
MMV_2022_21_MAGDALENA.csv -> utf-16-le, (219065, 21)
MMV_2022_23_NARIÑO.csv -> utf-16-le, (228868, 21)
MMV_2022_24_RISARALDA.csv -> utf-16-le, (176662, 21)
MMV_2022_25_NORTE_DE_SAN.csv -> utf-16-le, (293554, 21)
MMV_2022_26_QUINDIO.csv -> utf-16-le, (108217, 21)
MMV_2022_27_SANTANDER.csv -> utf-16-le, (446213, 21)
MMV_2022_28_SUCRE.csv -> utf-16-le, (155338, 21)
MMV_2022_29_TOLIMA.csv -> utf-16-le, (271284, 21)
MMV_2022_31_VALLE.csv -> utf-16-le, (932413, 21)
MMV_2022_40_ARAUCA.csv -> utf-16-le, (42023, 21)
MMV_2022_44_CAQUETA.csv -> utf-16-le, (66555, 21)
MMV_2022_46_CASANARE.csv -> utf-16-le, (60505, 21)
MMV_2022_48_LA_GUAJIRA.csv -> utf-16-le, (128232, 21)
MMV_2022_50_GUAINIA.csv -> utf-16-le, (6923, 21)
MMV_2022_52_META.csv -> utf-16-le, (165904, 21)
MMV_2022_54_GUAVIARE.csv -> utf-16-le, (12676, 21)
MMV_2022_56_SAN_ANDRES.csv -> utf-16-le, (9809, 21)
MMV_2022_60_AMAZONAS.csv -> utf-16-le, (11348, 21)
MMV_2022_64_PUTUMAYO.csv -> utf-16-le, (49551, 21)
MMV_2022_68_VAUPES.csv -> utf-16-le, (4390, 21)
MMV_2022_72_VICHADA.csv -> utf-16-le, (10389, 21)
MMV_2022_88_CONSULADOS.csv falló con utf-16-le: EmptyDataError
MMV_2022_88_CONSULADOS.csv -> utf-8, (87303, 1)
Shape final: (9325411, 22)
Columnas: ['Código Departamento', 'Nombre Departamento', 'Código Municipio', 'Nombre Municipio', 'Código Zona', 'Código Puesto', 'Nombre Puesto', 'Mesa', 'Código Comuna', 'Nombre Comuna', 'Código Corporación', 'Nombre Corporación', 'Código Circunscripción', 'Nombre Circunscripción', 'Código CITREP', 'Nombre CITREP', 'Código Partido', 'Nombre Partido', 'Código Candidato', 'Nombre Candidato', 'Total Votos', 'Código Departamento;Nombre Departamento;Código Municipio;Nombre Municipio;Código Zona;Código Puesto;Nombre Puesto;Mesa;Código Comuna;Nombre Comuna;Código Corporación;Nombre Corporación;Código Circunscripción;Nombre Circunscripción;Código CITREP;Nombre CITREP;Código Partido;Nombre Partido;Código Candidato;Nombre Candidato;Total Votos']

In [32]:
import pandas as pd
from pathlib import Path

carpeta = Path(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\2021-actualidad\2022")

# 1. Departamentos (todos excepto 88_CONSULADOS)
archivos_dept = sorted(
    p for p in carpeta.glob("MMV_2022_*.csv")
    if "88_CONSULADOS" not in p.name
)

dfs = []
for archivo in archivos_dept:
    df = pd.read_csv(
        archivo,
        encoding="utf-16-le",
        sep=",",
        engine="python",
        on_bad_lines="skip"
    )
    dfs.append(df)

# 2. Consulados
archivo_consulados = carpeta / "MMV_2022_88_CONSULADOS.csv"
df_consulados = pd.read_csv(
    archivo_consulados,
    encoding="utf-8-sig",
    sep=";",
    engine="python",
    on_bad_lines="skip"
)
dfs.append(df_consulados)

# 3. Concatenar
df_congreso_2022 = pd.concat(dfs, ignore_index=True)

print("Shape final:", df_congreso_2022.shape)
print("Columnas:", df_congreso_2022.columns.tolist())

Shape final: (9325778, 21)
Columnas: ['Código Departamento', 'Nombre Departamento', 'Código Municipio', 'Nombre Municipio', 'Código Zona', 'Código Puesto', 'Nombre Puesto', 'Mesa', 'Código Comuna', 'Nombre Comuna', 'Código Corporación', 'Nombre Corporación', 'Código Circunscripción', 'Nombre Circunscripción', 'Código CITREP', 'Nombre CITREP', 'Código Partido', 'Nombre Partido', 'Código Candidato', 'Nombre Candidato', 'Total Votos']

In [33]:
# Exportar a Parquet (recomendado: snappy compression)
df_congreso_2022.to_parquet(
    r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\2021-actualidad\df_congreso_2022.parquet",
    index=False,
    compression="snappy"
)

In [34]:
query = """
SELECT *
FROM 
    df_congreso_2022
WHERE "Nombre Partido" LIKE '%NUEVO LIBERALISMO%'
"""

# Ejecutar la consulta y convertir el resultado a un nuevo DataFrame
df_22_sql = duckdb.sql(query).df()
df_22_sql.head(100)

,Código Departamento,Nombre Departamento,Código Municipio,Nombre Municipio,Código Zona,Código Puesto,Nombre Puesto,Mesa,Código Comuna,Nombre Comuna,...,Nombre Corporación,Código Circunscripción,Nombre Circunscripción,Código CITREP,Nombre CITREP,Código Partido,Nombre Partido,Código Candidato,Nombre Candidato,Total Votos
0,1,ANTIOQUIA,49,BELLO,99,80,SAN FELIX,6,12.0,12COMUNA 12 SAN FELIX,...,SENADO,1,NACIONAL,0,NO CITREP,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
1,1,ANTIOQUIA,49,BELLO,99,80,SAN FELIX,4,12.0,12COMUNA 12 SAN FELIX,...,SENADO,1,NACIONAL,0,NO CITREP,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
2,1,ANTIOQUIA,49,BELLO,6,6,IE JOSEFA CAMPOS,8,7.0,07COMUNA 7 ALTOS DE NIQUIA,...,SENADO,1,NACIONAL,0,NO CITREP,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
3,1,ANTIOQUIA,49,BELLO,6,6,IE JOSEFA CAMPOS,9,7.0,07COMUNA 7 ALTOS DE NIQUIA,...,SENADO,1,NACIONAL,0,NO CITREP,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
4,1,ANTIOQUIA,49,BELLO,6,6,IE JOSEFA CAMPOS,12,7.0,07COMUNA 7 ALTOS DE NIQUIA,...,SENADO,1,NACIONAL,0,NO CITREP,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,ANTIOQUIA,49,BELLO,2,2,COLEGIO PARROQUIAL SAN FCO DE ASIS,19,2.0,02COMUNA 2 MADERA,...,SENADO,1,NACIONAL,0,NO CITREP,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
96,1,ANTIOQUIA,49,BELLO,2,2,COLEGIO PARROQUIAL SAN FCO DE ASIS,23,2.0,02COMUNA 2 MADERA,...,SENADO,1,NACIONAL,0,NO CITREP,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
97,1,ANTIOQUIA,49,BELLO,2,2,COLEGIO PARROQUIAL SAN FCO DE ASIS,27,2.0,02COMUNA 2 MADERA,...,SENADO,1,NACIONAL,0,NO CITREP,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
98,1,ANTIOQUIA,49,BELLO,7,2,I.E FE Y ALEGRIA NUEVA GENERAC,1,8.0,08COMUNA 8 NIQUIA,...,SENADO,1,NACIONAL,0,NO CITREP,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1
99,1,ANTIOQUIA,49,BELLO,7,2,I.E FE Y ALEGRIA NUEVA GENERAC,18,8.0,08COMUNA 8 NIQUIA,...,SENADO,1,NACIONAL,0,NO CITREP,19,PARTIDO NUEVO LIBERALISMO,0,PARTIDO NUEVO LIBERALISMO,1

In [35]:
df_22_sql.to_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\output\22_congreso_nuevo_liberalismo.csv", index=False, encoding="utf-8-sig")

## Limpieza y unificación final

In [15]:
df1 = pd.read_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\Nuevo Liberalismo\80_88_nuevo_liberalismo.csv")
df2 = pd.read_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\Nuevo Liberalismo\22_congreso_nuevo_liberalismo.csv")
df3 = pd.read_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\Nuevo Liberalismo\23_territoriales_nuevo_liberalismo.csv")
df4 = pd.read_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\Nuevo Liberalismo\26_congreso_nuevo_liberalismo.csv")

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14142 entries, 0 to 14141
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_electoral      14142 non-null  int64
 1   ano               14142 non-null  int64
 2   tipo_eleccion     14142 non-null  object
 3   coddpto           14142 non-null  int64
 4   departamento      14142 non-null  object
 5   codmpio           14142 non-null  int64
 6   municipio         14142 non-null  object
 7   circunscripcion   14142 non-null  object
 8   codigo_partido    14142 non-null  int64
 9   primer_apellido   14142 non-null  object
 10  segundo_apellido  14142 non-null  object
 11  nombres           14142 non-null  object
 12  votos             14142 non-null  int64
 13  nombre_completo   14142 non-null  object
dtypes: int64(6), object(8)
memory usage: 1.5+ MB

In [16]:
df1.head()

,id_electoral,ano,tipo_eleccion,coddpto,departamento,codmpio,municipio,circunscripcion,codigo_partido,primer_apellido,segundo_apellido,nombres,votos,nombre_completo
0,319820007,1982,camara de representantes,19,cauca,19001,popayan,departamental,19790001,sin_dato,sin_dato,movimiento de izquierda nuevo liberal 82,1411,movimiento de izquierda nuevo liberal 82
1,319820007,1982,camara de representantes,19,cauca,19001,popayan,departamental,19790001,velasco,ramirez,omar henry,0,omar henry velasco ramirez
2,319820007,1982,camara de representantes,19,cauca,19022,almaguer,departamental,19790001,sin_dato,sin_dato,movimiento de izquierda nuevo liberal 82,5,movimiento de izquierda nuevo liberal 82
3,319820007,1982,camara de representantes,19,cauca,19022,almaguer,departamental,19790001,velasco,ramirez,omar henry,0,omar henry velasco ramirez
4,319820007,1982,camara de representantes,19,cauca,19050,argelia,departamental,19790001,sin_dato,sin_dato,movimiento de izquierda nuevo liberal 82,108,movimiento de izquierda nuevo liberal 82

In [21]:
import pandas as pd

# =========================================
# 1. Copiar df1 para no modificar el original
# =========================================

df1_limpio = df1.copy()

# =========================================
# 2. Eliminar columnas innecesarias
# =========================================

cols_a_eliminar = [
    'id_electoral',
    'circunscripcion',
    'codigo_partido',
    'primer_apellido',
    'segundo_apellido',
    'nombres'
]

df1_limpio = df1_limpio.drop(columns=cols_a_eliminar, errors='ignore')

# =========================================
# 3. Reemplazar valores en 'nombre_completo' ANTES de renombrar
# =========================================

reemplazos = {
    'movimiento de izquierda nuevo liberal 82': 'lista',
    'partido nuevo liberalismo larrarte rodriguez': 'larrarte rodriguez',
    'movimiento nuevo liberalismo': 'lista',
    'partido nuevo liberalismo quijano caballero': 'quijano caballero',
    'partido nuevo liberalismo': 'lista'
}

# Aplicar reemplazos (case-insensitive)
df1_limpio['nombre_completo'] = df1_limpio['nombre_completo'].str.lower().replace(reemplazos)

# =========================================
# 4. Renombrar columnas
# =========================================

df1_limpio = df1_limpio.rename(
    columns={
        'nombre_completo': 'candidato',
        'tipo_eleccion': 'corporacion'
    }
)

# =========================================
# 5. Verificar resultado
# =========================================

print("=== df1_limpio ===")
print("Shape:", df1_limpio.shape)
print("Columnas:", df1_limpio.columns.tolist())
print("\nValores únicos en 'candidato' después de limpiar:")
print(df1_limpio['candidato'].value_counts(dropna=False).head(20))

=== df1_limpio ===
Shape: (14142, 8)
Columnas: ['ano', 'corporacion', 'coddpto', 'departamento', 'codmpio', 'municipio', 'votos', 'candidato']

Valores únicos en 'candidato' después de limpiar:
candidato
lista                              6374
luis carlos galan sarmiento        1195
gabriel jaime norena henao          246
hernando aguilera blanco            230
carlos ardila ballesteros           170
luis barreto buitrago               140
german riano cano                   139
silvio de jesus mejia duque         125
pedro jaramillo monsalve            124
luis guillermo valencia jimenez     122
luis ivan marulanda gomez           122
alberto uribe mejia                 122
ivan de jesus restrepo gomez        122
jorge e londono ulloa               121
jorge eliecer maldonado             121
roberto sandoval ballesteros        121
jose corredor nunez                 117
rafael amador campos                117
alberto villamizar cardenas         117
cesar pardo villalba                117
Name: count, dtype: int64

In [30]:
# Añadir columna 'partido' con valor 'nuevo liberalismo' en todos los registros
df1_limpio['partido'] = 'nuevo liberalismo'

# Verificar
print("=== df1_limpio ===")
print("Shape:", df1_limpio.shape)
print("Columnas:", df1_limpio.columns.tolist())
print("\nValores únicos en 'partido':")
print(df1_limpio['partido'].value_counts(dropna=False))

=== df1_limpio ===
Shape: (14142, 9)
Columnas: ['ano', 'corporacion', 'coddpto', 'departamento', 'codmpio', 'municipio', 'votos', 'candidato', 'partido']

Valores únicos en 'partido':
partido
nuevo liberalismo    14142
Name: count, dtype: int64

In [27]:
df2_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188414 entries, 0 to 188413
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   coddpto       188414 non-null  int64
 1   departamento  188414 non-null  object
 2   codmpio       188414 non-null  int64
 3   municipio     188414 non-null  object
 4   corporacion   188414 non-null  object
 5   candidato     188414 non-null  object
 6   votos         188414 non-null  int64
dtypes: int64(3), object(4)
memory usage: 10.1+ MB

In [29]:
import pandas as pd

# =========================================
# 1. Copiar df2 para no modificar el original
# =========================================

df2_limpio = df2.copy()

# =========================================
# 2. Seleccionar solo las columnas equivalentes
# =========================================

cols_a_mantener = [
    'Código Departamento',
    'Nombre Departamento',
    'Código Municipio',
    'Nombre Municipio',
    'Nombre Corporación',
    'Nombre Candidato',
    'Total Votos'
]

df2_limpio = df2_limpio[cols_a_mantener]

# =========================================
# 3. Renombrar a esquema df1
# =========================================

mapa_columnas = {
    'Código Departamento': 'coddpto',
    'Nombre Departamento': 'departamento',
    'Código Municipio': 'codmpio',
    'Nombre Municipio': 'municipio',
    'Nombre Corporación': 'corporacion',
    'Nombre Candidato': 'candidato',
    'Total Votos': 'votos'
}

df2_limpio = df2_limpio.rename(columns=mapa_columnas)

# =========================================
# 4. Añadir columna 'partido' con valor 'nuevo liberalismo'
# =========================================

df2_limpio['partido'] = 'nuevo liberalismo'

# =========================================
# 5. Añadir columna 'ano' con valor 2022
# =========================================

df2_limpio['ano'] = 2022

# =========================================
# 6. Reemplazar 'PARTIDO NUEVO LIBERALISMO' por 'lista' en 'candidato'
# =========================================

df2_limpio['candidato'] = df2_limpio['candidato'].str.replace(
    'PARTIDO NUEVO LIBERALISMO',
    'lista',
    regex=False
)

# =========================================
# 7. Poner en minúscula y sin tildes todo el contenido
# =========================================

def quitar_tildes(texto):
    if isinstance(texto, str):
        reemplazos = str.maketrans(
            'áéíóúüñÁÉÍÓÚÜÑ',
            'aeiouunAEIOUUN'
        )
        return texto.translate(reemplazos).lower()
    return texto

# Aplicar a todas las columnas de texto
cols_texto = df2_limpio.select_dtypes(include=['object']).columns

for col in cols_texto:
    df2_limpio[col] = df2_limpio[col].apply(quitar_tildes)

# =========================================
# 8. Verificar resultado
# =========================================

print("=== df2_limpio ===")
print("Shape:", df2_limpio.shape)
print("Columnas:", df2_limpio.columns.tolist())
print("\nPrimeras 5 filas:")
print(df2_limpio.head())
print("\nValores únicos en 'candidato':")
print(df2_limpio['candidato'].value_counts(dropna=False).head(20))

=== df2_limpio ===
Shape: (188414, 9)
Columnas: ['coddpto', 'departamento', 'codmpio', 'municipio', 'corporacion', 'candidato', 'votos', 'partido', 'ano']

Primeras 5 filas:
   coddpto departamento  codmpio municipio corporacion candidato  votos  \
0        1    antioquia       49     bello      senado     lista      1
1        1    antioquia       49     bello      senado     lista      1
2        1    antioquia       49     bello      senado     lista      1
3        1    antioquia       49     bello      senado     lista      1
4        1    antioquia       49     bello      senado     lista      1

             partido   ano
0  nuevo liberalismo  2022
1  nuevo liberalismo  2022
2  nuevo liberalismo  2022
3  nuevo liberalismo  2022
4  nuevo liberalismo  2022

Valores únicos en 'candidato':
candidato
lista                                      106210
julia miranda londono                       12171
miguel andres silva moyano                   8117
german ricaurte camargo                      7851
diego escallon arango                        4929
fernando posada angel                        4676
tulia margarita isabel saenz madarriaga      4549
nicolas suarez casallas                      3505
ana victoria beltran ramirez                 3277
oscar javier urquijo cabrera                 3106
paola andrea moncayo escobar                 2885
diego fernando rivera fuquene                2868
nancy edith perez acevedo                    2614
nelson alberto reyes rojas                   2478
marco aurelio penaranda lozano               1749
gina liliam potes aguirre                    1677
joan antonio rodriguez gamboa                1455
ernesto gordillo triana                      1425
orlando beltran zapata                       1418
carlos felipe sarmiento rojas                1239
Name: count, dtype: int64

In [32]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 695629 entries, 0 to 695628
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Código Departamento     695629 non-null  int64
 1   Nombre Departamento     695629 non-null  object
 2   Código Municipio        695629 non-null  int64
 3   Nombre Municipio        695629 non-null  object
 4   Código Zona             695629 non-null  int64
 5   Código Puesto           695629 non-null  object
 6   Nombre Puesto           695629 non-null  object
 7   Mesa                    695629 non-null  int64
 8   Código Comuna           695629 non-null  int64
 9   Nombre Comuna           695629 non-null  object
 10  Código Corporación      695629 non-null  int64
 11  Nombre Corporación      695629 non-null  object
 12  Código Circunscripción  695629 non-null  int64
 13  Código Partido          695629 non-null  int64
 14  Nombre Partido          695629 non-null  object
 15  Código Candidato        695629 non-null  int64
 16  Nombre Candidato        695629 non-null  object
 17  Total Votos             695629 non-null  int64
dtypes: int64(10), object(8)
memory usage: 95.5+ MB

In [34]:
import pandas as pd

# =========================================
# 1. Copiar df3 para no modificar el original
# =========================================

df3_limpio = df3.copy()

# =========================================
# 2. Seleccionar solo las columnas equivalentes
# =========================================

cols_a_mantener = [
    'Código Departamento',
    'Nombre Departamento',
    'Código Municipio',
    'Nombre Municipio',
    'Nombre Corporación',
    'Nombre Candidato',
    'Nombre Partido',
    'Total Votos'
]

df3_limpio = df3_limpio[cols_a_mantener]

# =========================================
# 3. Renombrar a esquema df3
# =========================================

mapa_columnas = {
    'Código Departamento': 'coddpto',
    'Nombre Departamento': 'departamento',
    'Código Municipio': 'codmpio',
    'Nombre Municipio': 'municipio',
    'Nombre Corporación': 'corporacion',  # Si quieres guardar también el nombre
    'Nombre Candidato': 'candidato',
    'Nombre Partido': 'partido',
    'Total Votos': 'votos'
}

df3_limpio = df3_limpio.rename(columns=mapa_columnas)



# =========================================
# 4. Verificar resultado
# =========================================

print("=== df3_limpio ===")
print("Shape:", df3_limpio.shape)
print("Columnas:", df3_limpio.columns.tolist())
print("\nPrimeras 5 filas:")
print(df3_limpio.head())

=== df3_limpio ===
Shape: (695629, 8)
Columnas: ['coddpto', 'departamento', 'codmpio', 'municipio', 'corporacion', 'candidato', 'partido', 'votos']

Primeras 5 filas:
   coddpto departamento  codmpio municipio corporacion  \
0        1    ANTIOQUIA        1  MEDELLIN         JAL
1        1    ANTIOQUIA        1  MEDELLIN         JAL
2        1    ANTIOQUIA        1  MEDELLIN         JAL
3        1    ANTIOQUIA        1  MEDELLIN         JAL
4        1    ANTIOQUIA        1  MEDELLIN         JAL

                         candidato                    partido  votos
0     PAOLA STEFANIA GUISAO URREGO  PARTIDO NUEVO LIBERALISMO      1
1        PARTIDO NUEVO LIBERALISMO  PARTIDO NUEVO LIBERALISMO      1
2        PARTIDO NUEVO LIBERALISMO  PARTIDO NUEVO LIBERALISMO      2
3  JONATHAN ANDRES ALVAREZ MACHADO  PARTIDO NUEVO LIBERALISMO      2
4        PARTIDO NUEVO LIBERALISMO  PARTIDO NUEVO LIBERALISMO      3

In [36]:
import pandas as pd

# =========================================
# 1. Convertir todos los valores en minúscula y sin tildes
# =========================================

def quitar_tildes(texto):
    if isinstance(texto, str):
        reemplazos = str.maketrans(
            'áéíóúüñÁÉÍÓÚÜÑ',
            'aeiouunAEIOUUN'
        )
        return texto.translate(reemplazos).lower()
    return texto

# Aplicar a todas las columnas de texto
cols_texto = df3_limpio.select_dtypes(include=['object']).columns

for col in cols_texto:
    df3_limpio[col] = df3_limpio[col].apply(quitar_tildes)

# =========================================
# 2. Cambiar "PARTIDO NUEVO LIBERALISMO" por 'lista' en 'candidato'
# =========================================

df3_limpio['candidato'] = df3_limpio['candidato'].str.replace(
    'partido nuevo liberalismo',
    'lista',
    regex=False
)

# =========================================
# 3. Crear columna 'ano' con valor 2023
# =========================================

df3_limpio['ano'] = 2023

# =========================================
# 4. Verificar resultado
# =========================================

print("=== df3_limpio ===")
print("Shape:", df3_limpio.shape)
print("Columnas:", df3_limpio.columns.tolist())
print("\nValores únicos en 'candidato':")
print(df3_limpio['candidato'].value_counts(dropna=False).head(20))

=== df3_limpio ===
Shape: (695629, 9)
Columnas: ['coddpto', 'departamento', 'codmpio', 'municipio', 'corporacion', 'candidato', 'partido', 'votos', 'ano']

Valores únicos en 'candidato':
candidato
lista                                               41284
nuevo liberalismo en marcha                         18988
carlos fernando galan pachon                        17784
juan javier baena merlano                           14382
juan manuel diaz martinez                           10785
nuevo liberalismo- agrupacion politica en marcha    10185
ricardo andres correa mojica                         8316
jesus david araque mejia                             8163
cristina calderon restrepo                           7644
juan david quintero rubio                            7560
fernando lopez gutierrez                             7254
david hernando saavedra murcia                       6366
elkin jwiseb huertas carrasquilla                    5964
juan enrique aaron rivero                            5465
julian fernando silva cala                           5344
andres mauricio prieto sanchez                       4836
adriana marcela gutierrez castaneda                  4805
yesid fernando rivera contreras                      4566
evert rengifo hernandez                              4529
flor elva cardenas velandia                          4486
Name: count, dtype: int64

In [40]:
# Lista de valores a reemplazar por 'lista'
valores_a_reemplazar = [
    'nuevo liberalismo- agrupacion politica en marcha',
    'nuevo liberalismo - conservador -colombia just...',
    'partido de la u-nuevo liberalismo-colombia jus...',
    'nuevo liberalismo-nueva fuerza democratica',
    'u, nuevo liberalismo, mira',
    'coalicion nuevo liberalismo en marcha',
    'nuevo liberalismo - cambio radical',
    'nuevo liberalismo y mira al concejo',
    'coalicion nuevo liberalismo - dignidad y compr...',
    'coalicion nuevo liberalismo y mira',
    'colombia renaciente - nuevo liberalismo',
    'nuevo liberalismo en marcha',
    'nuevo liberalismo - mira',
    'dignidad & compromiso y nuevo liberalismo',
    'alianza verde nuevo liberalismo'
]

# Reemplazar todos estos valores por 'lista' en la columna 'candidato'
df3_limpio.loc[df3_limpio['candidato'].isin(valores_a_reemplazar), 'candidato'] = 'lista'

# Verificar
print("Valores únicos en 'candidato' después del reemplazo:")
print(df3_limpio['candidato'].value_counts(dropna=False).head(20))

Valores únicos en 'candidato' después del reemplazo:
candidato
lista                                  74105
carlos fernando galan pachon           17784
juan javier baena merlano              14382
juan manuel diaz martinez              10785
ricardo andres correa mojica            8316
jesus david araque mejia                8163
cristina calderon restrepo              7644
juan david quintero rubio               7560
fernando lopez gutierrez                7254
david hernando saavedra murcia          6366
elkin jwiseb huertas carrasquilla       5964
juan enrique aaron rivero               5465
julian fernando silva cala              5344
andres mauricio prieto sanchez          4836
adriana marcela gutierrez castaneda     4805
yesid fernando rivera contreras         4566
evert rengifo hernandez                 4529
flor elva cardenas velandia             4486
cesar augusto salamanca rojas           4483
jose ignacio gutierrez bolivar          4358
Name: count, dtype: int64

In [43]:
df4.head()

,DEP,DEPNOMBRE,MUN,MUNNOMBRE,ZONA,PUESTO,PUESNOMBRE,MESA,COMUCODIGO,COMUNOMBRE,CORCODIGO,CORNOMBRE,CIR,PAR,PARNOMBRE,CAN,CANCEDULA,CANNOMBRE,VOTOS
0,60,AMAZONAS,1,LETICIA,98,1,CARCEL,1,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,3
1,60,AMAZONAS,1,LETICIA,99,77,KILOMETRO 11,1,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,2
2,60,AMAZONAS,1,LETICIA,99,76,IE SAN JUAN BOSCO,1,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,5
3,60,AMAZONAS,1,LETICIA,2,3,IE SAGRADO CORAZON DE JESUS,1,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,3
4,60,AMAZONAS,1,LETICIA,2,3,IE SAGRADO CORAZON DE JESUS,2,0,NACIONAL,6,CONSULTAS,0,200,LA GRAN CONSULTA POR COLOMBIA,4,79589617.0,JUAN MANUEL GALAN PACHON,10

In [42]:
df4.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['DEP', 'DEPNOMBRE', 'MUN', 'MUNNOMBRE', 'ZONA', 'PUESTO', 'PUESNOMBRE',
       'MESA', 'COMUCODIGO', 'COMUNOMBRE', 'CORCODIGO', 'CORNOMBRE', 'CIR',
       'PAR', 'PARNOMBRE', 'CAN', 'CANCEDULA', 'CANNOMBRE', 'VOTOS'],
      dtype='object')>

In [45]:
df4_limpio = df4.copy()

# =========================================
# 2. Seleccionar solo las columnas equivalentes
# =========================================

cols_a_mantener = [
    'DEP',
    'DEPNOMBRE',
    'MUN',
    'MUNNOMBRE',
    'CORNOMBRE',
    'CANNOMBRE',
    'PARNOMBRE',
    'VOTOS'
]

df4_limpio = df4_limpio[cols_a_mantener]

# =========================================
# 3. Renombrar a esquema df4
# =========================================

mapa_columnas = {
    'DEP': 'coddpto',
    'DEPNOMBRE': 'departamento',
    'MUN': 'codmpio',
    'MUNNOMBRE': 'municipio',
    'CORNOMBRE': 'corporacion',  # Si quieres guardar también el nombre
    'CANNOMBRE': 'candidato',
    'PARNOMBRE': 'partido',
    'VOTOS': 'votos'
}

df4_limpio = df4_limpio.rename(columns=mapa_columnas)



# =========================================
# 4. Verificar resultado
# =========================================

print("=== df4_limpio ===")
print("Shape:", df4_limpio.shape)
print("Columnas:", df4_limpio.columns.tolist())
print("\nPrimeras 5 filas:")
print(df4_limpio.head())

=== df4_limpio ===
Shape: (194179, 8)
Columnas: ['coddpto', 'departamento', 'codmpio', 'municipio', 'corporacion', 'candidato', 'partido', 'votos']

Primeras 5 filas:
   coddpto departamento  codmpio municipio corporacion  \
0       60     AMAZONAS        1   LETICIA   CONSULTAS
1       60     AMAZONAS        1   LETICIA   CONSULTAS
2       60     AMAZONAS        1   LETICIA   CONSULTAS
3       60     AMAZONAS        1   LETICIA   CONSULTAS
4       60     AMAZONAS        1   LETICIA   CONSULTAS

                  candidato                        partido  votos
0  JUAN MANUEL GALAN PACHON  LA GRAN CONSULTA POR COLOMBIA      3
1  JUAN MANUEL GALAN PACHON  LA GRAN CONSULTA POR COLOMBIA      2
2  JUAN MANUEL GALAN PACHON  LA GRAN CONSULTA POR COLOMBIA      5
3  JUAN MANUEL GALAN PACHON  LA GRAN CONSULTA POR COLOMBIA      3
4  JUAN MANUEL GALAN PACHON  LA GRAN CONSULTA POR COLOMBIA     10

In [50]:
import pandas as pd

# =========================================
# 1. Minúsculas y quitar tildes
# =========================================

def quitar_tildes(texto):
    if isinstance(texto, str):
        reemplazos = str.maketrans(
            'áéíóúüñÁÉÍÓÚÜÑ',
            'aeiouunAEIOUUN'
        )
        return texto.translate(reemplazos).lower()
    return texto

# Aplicar a todas las columnas de texto
cols_texto = df4_limpio.select_dtypes(include=['object']).columns

for col in cols_texto:
    df4_limpio[col] = df4_limpio[col].apply(quitar_tildes)

# =========================================
# 2. Crear columna 'ano' con valor 2026
# =========================================

df4_limpio['ano'] = 2026

# =========================================
# 3. Reemplazar valores por 'lista' en 'candidato'
# =========================================

valores_a_reemplazar = [
    'cr-nuevo liberalismo',
    'partido nuevo liberalismo',
    'centro democratico- nuevo liberalismo-mira',
    'partido de la u, mira, nuevo liberalismo'
]

df4_limpio.loc[df4_limpio['candidato'].isin(valores_a_reemplazar), 'candidato'] = 'lista'

# =========================================
# 4. Verificar resultado
# =========================================

print("=== df4_limpio ===")
print("Shape:", df4_limpio.shape)
print("Columnas:", df4_limpio.columns.tolist())
print("\nValores únicos en 'candidato':")
print(df4_limpio['candidato'].value_counts(dropna=False).head(20))

=== df4_limpio ===
Shape: (194179, 9)
Columnas: ['coddpto', 'departamento', 'codmpio', 'municipio', 'corporacion', 'candidato', 'partido', 'votos', 'ano']

Valores únicos en 'candidato':
candidato
juan manuel galan pachon                       102634
lista                                           19248
juan carlos restrepo hoyos                      11768
maria de los angeles ardila hernandez            7240
centro democrãtico- nuevo liberalismo-mira      6070
fabian camilo rojas barrera                      5792
carlos alberto perez molina                      5772
hector josue camacho acosta                      4118
felipe de jesus zapata donado                    3542
daniel santos carrillo                           3052
nadia alexandra carreã‘o avella                  2828
vicente anibal ojeda martinez                    2816
vanessa diaz cepeda                              2734
oscar yovany montenegro salcedo                  2632
camilo andres astaiza puerta                     2260
laura cristina monroy bayona                     2208
mayra alejandra valencia balanta                 1570
arifa del socorro rincon rodriguez               1556
julio cesar aguirre leon                         1421
jaime castilla verjel                             931
Name: count, dtype: int64

In [51]:
# Reemplazo más flexible (contenga "centro democr" y "nuevo liberalismo")
mask = df4_limpio['candidato'].str.contains('centro democr', case=False, na=False)
df4_limpio.loc[mask, 'candidato'] = 'lista'

# Verificar
print(df4_limpio['candidato'].value_counts(dropna=False).head(20))

candidato
juan manuel galan pachon                 102634
lista                                     25318
juan carlos restrepo hoyos                11768
maria de los angeles ardila hernandez      7240
fabian camilo rojas barrera                5792
carlos alberto perez molina                5772
hector josue camacho acosta                4118
felipe de jesus zapata donado              3542
daniel santos carrillo                     3052
nadia alexandra carreã‘o avella            2828
vicente anibal ojeda martinez              2816
vanessa diaz cepeda                        2734
oscar yovany montenegro salcedo            2632
camilo andres astaiza puerta               2260
laura cristina monroy bayona               2208
mayra alejandra valencia balanta           1570
arifa del socorro rincon rodriguez         1556
julio cesar aguirre leon                   1421
jaime castilla verjel                       931
manuel felipe parra fletcher                764
Name: count, dtype: int64

In [56]:
df1_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14142 entries, 0 to 14141
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ano           14142 non-null  int64
 1   corporacion   14142 non-null  object
 2   coddpto       14142 non-null  int64
 3   departamento  14142 non-null  object
 4   codmpio       14142 non-null  int64
 5   municipio     14142 non-null  object
 6   votos         14142 non-null  int64
 7   candidato     14142 non-null  object
 8   partido       14142 non-null  object
dtypes: int64(4), object(5)
memory usage: 994.5+ KB

In [57]:
import pandas as pd
from pathlib import Path

# =========================================
# 1. Concatenar los 4 dataframes
# =========================================

df_maestro = pd.concat(
    [df1_limpio, df2_limpio, df3_limpio, df4_limpio],
    ignore_index=True
)

print("Shape base maestra:", df_maestro.shape)
print("Columnas:", df_maestro.columns.tolist())

# =========================================
# 2. Crear carpeta si no existe
# =========================================

ruta_salida = Path(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\master")
ruta_salida.mkdir(parents=True, exist_ok=True)

# =========================================
# 3. Guardar como Parquet
# =========================================

archivo_parquet = ruta_salida / "df_maestro_elecciones_limpio.parquet"

df_maestro.to_parquet(
    archivo_parquet,
    index=False,
    compression="snappy"
)

print("\nBase maestra guardada como Parquet en:", archivo_parquet)
print("Shape final:", df_maestro.shape)

Shape base maestra: (1092364, 9)
Columnas: ['ano', 'corporacion', 'coddpto', 'departamento', 'codmpio', 'municipio', 'votos', 'candidato', 'partido']

Base maestra guardada como Parquet en: C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\data\master\df_maestro_elecciones_limpio.parquet
Shape final: (1092364, 9)

## Fase 3

In [58]:
df_maestro.head()

,ano,corporacion,coddpto,departamento,codmpio,municipio,votos,candidato,partido
0,1982,camara de representantes,19,cauca,19001,popayan,1411,lista,nuevo liberalismo
1,1982,camara de representantes,19,cauca,19001,popayan,0,omar henry velasco ramirez,nuevo liberalismo
2,1982,camara de representantes,19,cauca,19022,almaguer,5,lista,nuevo liberalismo
3,1982,camara de representantes,19,cauca,19022,almaguer,0,omar henry velasco ramirez,nuevo liberalismo
4,1982,camara de representantes,19,cauca,19050,argelia,108,lista,nuevo liberalismo

In [61]:
# Obtener valores únicos de la columna 'departamento' como lista de texto
valores_unicos_departamento = df_maestro['departamento'].unique().tolist()

print("Valores únicos en 'departamento':")
print(valores_unicos_departamento)
print(f"\nTotal de valores únicos: {len(valores_unicos_departamento)}")

Valores únicos en 'departamento':
['cauca', 'meta', 'antioquia', 'atlantico', 'consulados', 'bolivar', 'boyaca', 'caldas', 'caqueta', 'cesar', 'cordoba', 'bogota dc', 'cundinamarca', 'choco', 'huila', 'la guajira', 'magdalena', 'narino', 'norte de santander', 'quindio', 'risaralda', 'santander', 'sucre', 'tolima', 'valle del cauca', 'arauca', 'casanare', 'putumayo', 'archipielago de san andres providencia y santa catalina', 'amazonas', 'guainia', 'guaviare', 'vaupes', 'vichada', 'comisaria del vichada', 'sin_dato', 'san andres', 'santafe de bogota dc', 'bogota d.c.', 'norte de san', 'valle', 'nariã‘o']

Total de valores únicos: 42

In [62]:
import numpy as np

# =========================================
# 1. Diccionario de reemplazos para 'departamento'
# =========================================

reemplazos_departamento = {
    'bogota dc': 'bogota',
    'santafe de bogota dc': 'bogota',
    'bogota d.c.': 'bogota',
    'valle': 'valle del cauca',
    'nariã‘o': 'narino',
    'norte de san': 'norte de santander',
    'san andres': 'san andres, providencia y santa catalina',
    'comisaria del vichada': 'vichada'# o 'desconocido' si prefieres
}

# =========================================
# 2. Aplicar reemplazos
# =========================================

df_maestro['departamento'] = df_maestro['departamento'].replace(reemplazos_departamento)

# =========================================
# 3. Verificar resultado
# =========================================

valores_unicos_departamento = df_maestro['departamento'].unique().tolist()

print("Valores únicos en 'departamento' después de limpiar:")
print(sorted(valores_unicos_departamento))
print(f"\nTotal de valores únicos: {len(valores_unicos_departamento)}")

Valores únicos en 'departamento' después de limpiar:
['amazonas', 'antioquia', 'arauca', 'archipielago de san andres providencia y santa catalina', 'atlantico', 'bogota', 'bolivar', 'boyaca', 'caldas', 'caqueta', 'casanare', 'cauca', 'cesar', 'choco', 'consulados', 'cordoba', 'cundinamarca', 'guainia', 'guaviare', 'huila', 'la guajira', 'magdalena', 'meta', 'narino', 'norte de santander', 'putumayo', 'quindio', 'risaralda', 'san andres, providencia y santa catalina', 'santander', 'sin_dato', 'sucre', 'tolima', 'valle del cauca', 'vaupes', 'vichada']

Total de valores únicos: 36

In [63]:
# Reemplazar el valor restante
df_maestro.loc[df_maestro['departamento'] == 'archipielago de san andres providencia y santa catalina', 'departamento'] = 'san andres, providencia y santa catalina'

# Verificar
valores_unicos_departamento = df_maestro['departamento'].unique().tolist()

print("Valores únicos en 'departamento' después de limpiar:")
print(sorted(valores_unicos_departamento))
print(f"\nTotal de valores únicos: {len(valores_unicos_departamento)}")

Valores únicos en 'departamento' después de limpiar:
['amazonas', 'antioquia', 'arauca', 'atlantico', 'bogota', 'bolivar', 'boyaca', 'caldas', 'caqueta', 'casanare', 'cauca', 'cesar', 'choco', 'consulados', 'cordoba', 'cundinamarca', 'guainia', 'guaviare', 'huila', 'la guajira', 'magdalena', 'meta', 'narino', 'norte de santander', 'putumayo', 'quindio', 'risaralda', 'san andres, providencia y santa catalina', 'santander', 'sin_dato', 'sucre', 'tolima', 'valle del cauca', 'vaupes', 'vichada']

Total de valores únicos: 35

In [64]:
# Obtener valores únicos de 'municipio' ordenados
valores_unicos_municipio = sorted(df_maestro['municipio'].unique().tolist())

print("Valores únicos en 'municipio':")
for i, val in enumerate(valores_unicos_municipio, 1):
    print(f"{i}. {val}")

print(f"\nTotal de valores únicos: {len(valores_unicos_municipio)}")

Valores únicos en 'municipio':
1. abejorral
2. abrego
3. abriaqui
4. acacias
5. acandi
6. acevedo
7. achi
8. agrado
9. agua de dios
10. aguachica
11. aguada
12. aguadas
13. aguazul
14. agustin codazzi
15. aipe
16. alban
17. alban (san jose)
18. albania
19. alcala
20. aldana
21. alejandria
22. alemania
23. algarrobo
24. algeciras
25. almaguer
26. almeida
27. alpujarra
28. altamira
29. alto baudo
30. alto baudo (pie de pato)
31. altos del rosario
32. alvarado
33. amaga
34. amalfi
35. ambalema
36. anapoima
37. ancuya
38. andalucia
39. andes
40. angelopolis
41. angostura
42. anolaima
43. anori
44. anserma
45. ansermanuevo
46. antillas holandesas
47. antioquia
48. anza
49. anzoategui
50. apartado
51. apia
52. apulo
53. aquitania
54. aquitania (puebloviejo)
55. aracataca
56. aranzazu
57. aratoca
58. arauca
59. arauquita
60. arbelaez
61. arbeleez
62. arboleda
63. arboleda (berruecos)
64. arboledas
65. arboletes
66. arcabuco
67. arenal
68. argelia
69. argentina
70. ariguani
71. ariguani (el dificil)
72. arjona
73. armenia
74. armero
75. armero (guayabal)
76. arroyo hondo
77. aruba
78. arzerbaiyan
79. astrea
80. ataco
81. atrato (yuto)
82. australia
83. austria
84. ayapel
85. bagado
86. bahia solano
87. bahia solano (mutis)
88. bajo baudo
89. bajo baudo (pizarro)
90. balboa
91. baranoa
92. baraya
93. barbacoas
94. barbosa
95. barichara
96. barranca de upia
97. barrancabermeja
98. barrancas
99. barranco de loba
100. barrancominas
101. barranquilla
102. becerril
103. belalcazar
104. belen
105. belen de los andaquies
106. belen de umbria
107. belgica
108. bello
109. belmira
110. beltran
111. berbeo
112. betania
113. beteitiva
114. betulia
115. bituima
116. boavita
117. bochalema
118. bogota d e
119. bogota dc
120. bogota. d.c.
121. bojaca
122. bojaya
123. bojaya (bellavista)
124. bolivar
125. bolivia
126. bosconia
127. boyaca
128. brasil
129. brice?o
130. briceno
131. briceã‘o
132. bucaramanga
133. bucarasica
134. buenaventura
135. buenavista
136. buenos aires
137. buenos aires (pacoa)
138. buesaco
139. buga
140. bugalagrande
141. bulgaria
142. buritica
143. busbanza
144. ca?asgordas
145. cabrera
146. cabuyaro
147. cacahual
148. caceres
149. cachipay
150. cachira
151. cacota
152. caicedo
153. caicedonia
154. caimito
155. cajamarca
156. cajibio
157. cajica
158. calamar
159. calara
160. calarca
161. caldas
162. caldono
163. cali
164. california
165. calima
166. calima (darien)
167. caloto
168. campamento
169. campo de la cruz
170. campoalegre
171. campohermoso
172. canada
173. canalete
174. canasgordas
175. candelaria
176. cantagallo
177. caparrapi
178. capitanejo
179. caqueza
180. caracoli
181. caramanta
182. carcasi
183. carepa
184. carmen de apicala
185. carmen de carupa
186. carmen de viboral
187. carmen del darien
188. carolina
189. cartagena
190. cartagena de indias
191. cartagena del chaira
192. cartago
193. caruru
194. casabianca
195. castilla la nueva
196. caucasia
197. cepita
198. cerete
199. cerinza
200. cerrito
201. cerro de san antonio
202. certegui
203. chachagui
204. chaguani
205. chalan
206. chameza
207. chaparral
208. charala
209. charta
210. chia
211. chigorodo
212. chile
213. chima
214. chimichagua
215. china republica popular
216. chinacota
217. chinavita
218. chinchina
219. chinu
220. chipaque
221. chipata
222. chiquinquira
223. chiquiza
224. chiriguana
225. chiscas
226. chita
227. chitaga
228. chitaraque
229. chivata
230. chivolo
231. chivor
232. choachi
233. choconta
234. cicuco
235. cienaga
236. cienaga de oro
237. cienega
238. cimitarra
239. circasia
240. cisneros
241. ciudad bolivar
242. clemencia
243. cocorna
244. coello
245. cogua
246. colombia
247. colon
248. colon (genova)
249. coloso
250. coloso (ricaurte)
251. combita
252. concepcion
253. concordia
254. condoto
255. confines
256. consaca
257. contadero
258. contratacion
259. convencion
260. copacabana
261. coper
262. cordoba
263. corea del sur
264. corinto
265. coromoro
266. corozal
267. corrales
268. costa de marfil
269. costa rica
270. cota
271. cotorra (bongo)
272. covarachia
273. cove?as
274. coveã‘as
275. coyaima
276. cravo norte
277. cuaspud
278. cuaspud (carlosama)
279. cuaspud carlosama
280. cuba
281. cubara
282. cubarral
283. cucaita
284. cucunuba
285. cucuta
286. cucutilla
287. cuitiva
288. cumaral
289. cumaribo
290. cumbal
291. cumbitara
292. cunday
293. curazao
294. curillo
295. curiti
296. curumani
297. dabeiba
298. dagua
299. dibulla
300. dinamarca
301. distraccion
302. dolores
303. don matias
304. donmatias
305. dosquebradas
306. duitama
307. durania
308. ebejico
309. ecuador
310. egipto
311. el aguila
312. el bagre
313. el banco
314. el cairo
315. el calvario
316. el canton del san pablo (man.
317. el carmen
318. el carmen de atrato
319. el carmen de bolivar
320. el carmen de chucuri
321. el carmen de viboral
322. el castillo
323. el cerrito
324. el charco
325. el cocuy
326. el colegio
327. el copey
328. el doncello
329. el dorado
330. el dovio
331. el encanto
332. el espino
333. el guacamayo
334. el guamo
335. el litoral del san juan
336. el molino
337. el paso
338. el paujil
339. el pe?ol
340. el pe?on
341. el penol
342. el penon
343. el peã‘ol
344. el peã‘on
345. el pi?on
346. el pinon
347. el piã‘on
348. el playon
349. el reten
350. el retorno
351. el roble
352. el rosal
353. el rosario
354. el salvador
355. el santuario
356. el tablon
357. el tablon de gomez
358. el tambo
359. el tarra
360. el zulia
361. elias
362. emiratos arabes unidos
363. encino
364. enciso
365. entrerrios
366. envigado
367. espana
368. espaã‘a
369. espinal
370. estados unidos
371. facatativa
372. falan
373. filadelfia
374. filandia
375. finlandia
376. firavitoba
377. flandes
378. florencia
379. floresta
380. florian
381. florida
382. floridablanca
383. fomeque
384. fonseca
385. fortul
386. fosca
387. francia
388. francisco pizarro
389. francisco pizarro (salahonda)
390. fredonia
391. fresno
392. frontino
393. fuente de oro
394. fundacion
395. funes
396. funza
397. fuquene
398. fusagasuga
399. gachala
400. gachancipa
401. gachantiva
402. gacheta
403. galan
404. galapa
405. galeras
406. galeras (nueva granada)
407. gama
408. gamarra
409. gambita
410. gameza
411. garagoa
412. garzon
413. genova
414. ghana
415. gigante
416. ginebra
417. giraldo
418. girardot
419. girardota
420. giron
421. gomez plata
422. gonzalez
423. gramalote
424. granada
425. grecia
426. guaca
427. guacamayas
428. guacari
429. guachene
430. guacheta
431. guachucal
432. guadalajara de buga
433. guadalupe
434. guaduas
435. guaitarilla
436. gualmatan
437. guamal
438. guamo
439. guapi
440. guapota
441. guaranda
442. guarne
443. guasca
444. guatape
445. guataqui
446. guatavita
447. guatemala
448. guateque
449. guatica
450. guavata
451. guayabal de siquima
452. guayabetal
453. guayata
454. guepsa
455. guican
456. guican de la sierra
457. gutierrez
458. guyana
459. hacari
460. haiti
461. hatillo de loba
462. hato
463. hato corozal
464. hatonuevo
465. heliconia
466. herran
467. herveo
468. hispania
469. hobo
470. honda
471. honduras
472. hong kong (china)
473. hungria
474. ibague
475. icononzo
476. iles
477. imues
478. india
479. indonesia
480. inglaterra
481. inirida
482. inza
483. ipiales
484. iquira
485. iran
486. irlanda
487. isnos
488. israel
489. istmina
490. itagui
491. italia
492. itsmina
493. ituango
494. iza
495. jamaica
496. jambalo
497. jamundi
498. japon
499. jardin
500. jenesano
501. jerico
502. jerusalen
503. jesus maria
504. jordan
505. juan de acosta
506. junin
507. jurado
508. kenia
509. la apartada (frontera)
510. la argentina
511. la argentina (plata vieja)
512. la belleza
513. la calera
514. la capilla
515. la ceja
516. la celia
517. la chorrera
518. la cruz
519. la cumbre
520. la dorada
521. la esperanza
522. la estrella
523. la florida
524. la gloria
525. la jagua de ibirico
526. la jagua del pilar
527. la llanada
528. la macarena
529. la merced
530. la mesa
531. la monta?ita
532. la montanita
533. la montaã‘ita
534. la palma
535. la paz
536. la pe?a
537. la pedrera
538. la pena
539. la peã‘a
540. la pintada
541. la plata
542. la playa
543. la primavera
544. la salina
545. la sierra
546. la tebaida
547. la tola
548. la union
549. la uvita
550. la vega
551. la victoria
552. la virginia
553. labateca
554. labranzagrande
555. landazuri
556. lebrija
557. leiva
558. lejanias
559. lenguazaque
560. lerida
561. leticia
562. libano
563. liborina
564. linares
565. lloro
566. lopez
567. lopez (micay)
568. lopez de micay
569. lorica
570. los andes
571. los andes (sotomayor)
572. los cordobas
573. los palmitos
574. los patios
575. los santos
576. lourdes
577. luruaco
578. luxemburgo
579. macanal
580. macaravita
581. maceo
582. macheta
583. madrid
584. magangue
585. magui
586. magui (payan)
587. mahates
588. maicao
589. majagual
590. malaga
591. malambo
592. malasia
593. mallama
594. mallama (piedrancha)
595. manati
596. manaure
597. manaure balcon del cesar
598. manaure balcon del cesar (mana
599. mani
600. manizales
601. manta
602. manzanares
603. mapiripan
604. margarita
605. maria la baja
606. marinilla
607. maripi
608. mariquita
609. marmato
610. marquetalia
611. marruecos
612. marsella
613. marulanda
614. matanza
615. medellin
616. medina
617. medio atrato (bete)
618. medio baudo (puerto meluk)
619. medio san juan
620. melgar
621. mercaderes
622. mesetas
623. mexico
624. milan
625. miraflores
626. miranda
627. miriti  parana
628. miriti parana
629. mistrato
630. mitu
631. mo?itos
632. mocoa
633. mogotes
634. molagavita
635. momil
636. mompos
637. mongua
638. mongui
639. moniquira
640. monitos
641. montebello
642. montecristo
643. montelibano
644. montenegro
645. monteria
646. monterrey
647. morales
648. morelia
649. morichal (papunagua)
650. morroa
651. mosquera
652. motavita
653. moã‘itos
654. murillo
655. murindo
656. mutata
657. mutiscua
658. muzo
659. nari?o
660. narino
661. nariã‘o
662. nataga
663. natagaima
664. nechi
665. necocli
666. neira
667. neiva
668. nemocon
669. nicaragua
670. nigeria
671. nilo
672. nimaima
673. nobsa
674. nocaima
675. norcasia
676. norosi
677. noruega
678. novita
679. nueva antioquia
680. nueva granada
681. nueva zelandia
682. nuevo belen de bajira
683. nuevo colon
684. nunchia
685. nuqui
686. obando
687. oca?a
688. ocamonte
689. ocana
690. ocaã‘a
691. oiba
692. oicata
693. olaya
694. olaya herrera
695. onzaga
696. oporapa
697. orito
698. orocue
699. ortega
700. ospina
701. otanche
702. ovejas
703. pachavita
704. pacho
705. pacoa
706. pacora
707. padilla
708. paez
709. paez (belalcazar)
710. paicol
711. pailitas
712. paime
713. paipa
714. paises bajos
715. pajarito
716. palermo
717. palestina
718. palmar
719. palmar de varela
720. palmas del socorro
721. palmas socorro
722. palmira
723. palmito
724. palocabildo
725. pamplona
726. pamplonita
727. pana pana (campo alegre)
728. panama
729. pandi
730. panqueba
731. paraguay
732. paramo
733. paratebueno
734. paratebueno (la naguaya)
735. pasca
736. pasto
737. patia
738. patia (el bordo)
739. pauna
740. paya
741. paz de ariporo
742. paz de ariporo (moreno)
743. paz de rio
744. pe?ol
745. pedraza
746. pelaya
747. penol
748. pensilvania
749. peque
750. pereira
751. peru
752. pesca
753. piamonte
754. piedecuesta
755. piedras
756. piendamo
757. piendamo  tunia
758. pijao
759. piji?o del carmen
760. pijino del carmen
761. pijiã‘o del carmen
762. pinchote
763. pinillos
764. piojo
765. pisba
766. pisva
767. pital
768. pitalito
769. pivijay
770. planadas
771. planeta rica
772. plato
773. policarpa
774. polonia
775. polonuevo
776. ponedera
777. popayan
778. pore
779. portugal
780. potosi
781. pradera
782. prado
783. providencia
784. pueblo bello
785. pueblo nuevo
786. pueblo rico
787. pueblorrico
788. puebloviejo
789. puente nacional
790. puerres
791. puerto arica
792. puerto asis
793. puerto berrio
794. puerto boyaca
795. puerto caicedo
796. puerto carre?o
797. puerto carreno
798. puerto carreã‘o
799. puerto colombia
800. puerto concordia
801. puerto escondido
802. puerto gaitan
803. puerto guzman
804. puerto leguizamo
805. puerto libertador
806. puerto lleras
807. puerto lopez
808. puerto nare
809. puerto nare (la magdalena)
810. puerto nare-la magdalena
811. puerto nari?o
812. puerto narino
813. puerto nariã‘o
814. puerto parra
815. puerto rico
816. puerto rondon
817. puerto salgar
818. puerto santander
819. puerto tejada
820. puerto triunfo
821. puerto wilches
822. puli
823. pupiales
824. purace
825. purace (coconuco)
826. purificacion
827. purisima
828. purisima de la concepcion
829. quebradanegra
830. quetame
831. quibdo
832. quimbaya
833. quinchia
834. quipama
835. quipile
836. ragonvalia
837. ramiriqui
838. raquira
839. recetor
840. regidor
841. remedios
842. remolino
843. repelon
844. republica de filipinas
845. republica de singapur
846. republica democratica alemania
847. republica dominicana
848. republica socialista de vietna
849. republica socialista devietnam
850. restrepo
851. retiro
852. ricaurte
853. rio de oro
854. rio iro
855. rio quito (paimado)
856. rio viejo
857. rioblanco
858. riofrio
859. riohacha
860. rionegro
861. riosucio
862. rioviejo
863. risaralda
864. rivera
865. roberto payan
866. roberto payan (san jose)
867. roldanillo
868. roncesvalles
869. rondon
870. rosas
871. rovira
872. rumania
873. rusia
874. sabana de torres
875. sabanagrande
876. sabanalarga
877. sabanas de san angel
878. sabaneta
879. saboya
880. sacama
881. sachica
882. sahagun
883. saladoblanco
884. salamina
885. salazar
886. salda?a
887. saldana
888. saldaã‘a
889. salento
890. salgar
891. samaca
892. samana
893. samaniego
894. sampues
895. san agustin
896. san alberto
897. san andres
898. san andres de cuerquia
899. san andres de sotavento
900. san andres de tumaco
901. san antero
902. san antonio
903. san antonio del tequendama
904. san benito
905. san benito abad
906. san bernardo
907. san bernardo del viento
908. san calixto
909. san carlos
910. san carlos de guaroa
911. san carlos guaroa
912. san cayetano
913. san cristobal
914. san diego
915. san eduardo
916. san estanislao
917. san felipe
918. san fernando
919. san francisco
920. san gil
921. san jacinto
922. san jacinto del cauca
923. san jeronimo
924. san joaquin
925. san jose
926. san jose de cucuta
927. san jose de fragua
928. san jose de la monta?a
929. san jose de la montana
930. san jose de miranda
931. san jose de ocune
932. san jose de pare
933. san jose de toluviejo
934. san jose de ure
935. san jose del fragua
936. san jose del guaviare
937. san jose del palmar
938. san juan de arama
939. san juan de betulia
940. san juan de betulia (betulia)
941. san juan de rioseco
942. san juan de uraba
943. san juan del cesar
944. san juan nepomuceno
945. san juanito
946. san lorenzo
947. san luis
948. san luis de gaceno
949. san luis de palenque
950. san luis de since
951. san marcos
952. san martin
953. san martin de loba
954. san martin de los llanos
955. san mateo
956. san miguel
957. san miguel (la dorada)
958. san miguel de sema
959. san onofre
960. san pablo
961. san pablo borbur
962. san pablo de borbur
963. san pedro
964. san pedro de cartago
965. san pedro de los milagros
966. san pedro de uraba
967. san pelayo
968. san rafael
969. san roque
970. san sebastian
971. san sebastian de buenavista
972. san sebastian de mariquita
973. san vicente
974. san vicente de chucuri
975. san vicente del caguan
976. san vicente ferrer
977. san zenon
978. sandona
979. santa ana
980. santa barbara
981. santa barbara (iscuande)
982. santa barbara de pinto
983. santa catalina
984. santa cruz de mompox
985. santa fe de antioquia
986. santa helena del opon
987. santa isabel
988. santa lucia
989. santa maria
990. santa marta
991. santa rita
992. santa rosa
993. santa rosa de cabal
994. santa rosa de osos
995. santa rosa de viterbo
996. santa rosa del sur
997. santa rosalia
998. santa sofia
999. santacruz
1000. santacruz (guachaves)
1001. santafe de bogota dc
1002. santana
1003. santander de quilichao
1004. santiago
1005. santiago de tolu
1006. santo domingo
1007. santo tomas
1008. santuario
1009. sapuyes
1010. saravena
1011. sardinata
1012. sasaima
1013. sativanorte
1014. sativasur
1015. segovia
1016. sesquile
1017. sevilla
1018. siachoque
1019. sibate
1020. sibundoy
1021. silos
1022. silvania
1023. silvia
1024. simacota
1025. simijaca
1026. simiti
1027. sin_dato
1028. since
1029. sincelejo
1030. sipi
1031. sitionuevo
1032. soacha
1033. soata
1034. socha
1035. socorro
1036. socota
1037. sogamoso
1038. solano
1039. soledad
1040. solita
1041. somondoco
1042. sonson
1043. sopetran
1044. soplaviento
1045. sopo
1046. sora
1047. soraca
1048. sotaquira
1049. sotara
1050. sotara (paispamba)
1051. sotara paispamba
1052. suaita
1053. suan
1054. suarez
1055. suaza
1056. subachoque
1057. sucre
1058. sudafrica
1059. suecia
1060. suesca
1061. suiza
1062. supata
1063. supia
1064. surata
1065. susa
1066. susacon
1067. sutamarchan
1068. sutatausa
1069. sutatenza
1070. tabio
1071. tado
1072. tailandia
1073. talaigua nuevo
1074. tamalameque
1075. tamara
1076. tame
1077. tamesis
1078. taminango
1079. tangua
1080. taraira
1081. tarapaca
1082. taraza
1083. tarqui
1084. tarso
1085. tasco
1086. tauramena
1087. tausa
1088. tello
1089. tena
1090. tenerife
1091. tenjo
1092. tenza
1093. teorama
1094. teruel
1095. tesalia
1096. tesalia (carnicerias)
1097. tibacuy
1098. tibana
1099. tibasosa
1100. tibirita
1101. tibu
1102. tierralta
1103. timana
1104. timbio
1105. timbiqui
1106. tinjaca
1107. tipacoque
1108. tiquisio (pto. rico)
1109. titiribi
1110. toca
1111. tocaima
1112. tocancipa
1113. togui
1114. toledo
1115. tolu
1116. toluviejo
1117. tona
1118. topaga
1119. topaipi
1120. toribio
1121. toro
1122. tota
1123. totoro
1124. trinidad
1125. trinidad y tobago
1126. trujillo
1127. tubara
1128. tuchin
1129. tulua
1130. tumaco
1131. tunja
1132. tunungua
1133. tuquerres
1134. turbaco
1135. turbana
1136. turbo
1137. turmeque
1138. turquia
1139. tuta
1140. tutasa
1141. tutaza
1142. ubala
1143. ubaque
1144. ubate
1145. ulloa
1146. umbita
1147. une
1148. unguia
1149. union panamericana (las animas
1150. uramita
1151. uribe
1152. uribia
1153. urrao
1154. uruguay
1155. urumita
1156. usiacuri
1157. utica
1158. valdivia
1159. valencia
1160. valle de san jose
1161. valle de san juan
1162. valle del guamuez (la hormiga)
1163. valledupar
1164. valparaiso
1165. vegachi
1166. velez
1167. venadillo
1168. venecia
1169. venezuela
1170. ventaquemada
1171. vergara
1172. versalles
1173. vetas
1174. viani
1175. victoria
1176. vigia del fuerte
1177. vijes
1178. villa caro
1179. villa de leiva
1180. villa de leyva
1181. villa de san diego de ubate
1182. villa del rosario
1183. villa rica
1184. villagarzon
1185. villagomez
1186. villahermosa
1187. villamaria
1188. villanueva
1189. villapinzon
1190. villarrica
1191. villavicencio
1192. villavieja
1193. villeta
1194. viota
1195. viracacha
1196. vista hermosa
1197. vistahermosa
1198. viterbo
1199. yacopi
1200. yacuanquer
1201. yaguara
1202. yali
1203. yarumal
1204. yavarate
1205. yolombo
1206. yondo
1207. yondo-casabe
1208. yopal
1209. yotoco
1210. yugoslavia
1211. yumbo
1212. zambrano
1213. zapatoca
1214. zapayan
1215. zaragoza
1216. zarzal
1217. zetaquira
1218. zipacon
1219. zipaquira
1220. zona bananera (sevilla)

Total de valores únicos: 1220

In [65]:
import numpy as np

# =========================================
# 1. Diccionario de reemplazos para 'municipio'
# =========================================

reemplazos_municipio = {
    # Caracteres extraños / ñ
    'brice?o': 'briceno',
    'briceã‘o': 'briceno',
    'ca?asgordas': 'canasgordas',
    'cove?as': 'covenas',
    'coveã‘as': 'covenas',
    'el pe?ol': 'el penol',
    'el peã‘ol': 'el penol',
    'el pe?on': 'el penon',
    'el peã‘on': 'el penon',
    'el pi?on': 'el pinon',
    'el piã‘on': 'el pinon',
    'la monta?ita': 'la montanita',
    'la montaã‘ita': 'la montanita',
    'la pe?a': 'la pena',
    'la peã‘a': 'la pena',
    'mo?itos': 'monitos',
    'moã‘itos': 'monitos',
    'nari?o': 'narino',
    'nariã‘o': 'narino',
    'oca?a': 'ocana',
    'ocaã‘a': 'ocana',
    'piji?o del carmen': 'pijino del carmen',
    'pijiã‘o del carmen': 'pijino del carmen',
    'puerto carre?o': 'puerto carreno',
    'puerto carreã‘o': 'puerto carreno',
    'puerto nari?o': 'puerto narino',
    'puerto nariã‘o': 'puerto narino',
    'salda?a': 'saldana',
    'saldaã‘a': 'saldana',
    'san jose de la monta?a': 'san jose de la montana',

    # Bogotá
    'bogota d e': 'bogota',
    'bogota dc': 'bogota',
    'bogota. d.c.': 'bogota',
    'santafe de bogota dc': 'bogota',

    # Paréntesis / cabeceras equivalentes
    'alban (san jose)': 'alban',
    'alto baudo (pie de pato)': 'alto baudo',
    'aquitania (puebloviejo)': 'aquitania',
    'arboleda (berruecos)': 'arboleda',
    'ariguani (el dificil)': 'ariguani',
    'armero (guayabal)': 'armero',
    'atrato (yuto)': 'atrato',
    'bahia solano (mutis)': 'bahia solano',
    'bajo baudo (pizarro)': 'bajo baudo',
    'bojaya (bellavista)': 'bojaya',
    'buenos aires (pacoa)': 'buenos aires',
    'calima (darien)': 'calima',
    'colon (genova)': 'colon',
    'coloso (ricaurte)': 'coloso',
    'cotorra (bongo)': 'cotorra',
    'cuaspud (carlosama)': 'cuaspud',
    'francisco pizarro (salahonda)': 'francisco pizarro',
    'galeras (nueva granada)': 'galeras',
    'la apartada (frontera)': 'la apartada',
    'la argentina (plata vieja)': 'la argentina',
    'lopez (micay)': 'lopez',
    'los andes (sotomayor)': 'los andes',
    'magui (payan)': 'magui',
    'mallama (piedrancha)': 'mallama',
    'medio atrato (bete)': 'medio atrato',
    'medio baudo (puerto meluk)': 'medio baudo',
    'paez (belalcazar)': 'paez',
    'paratebueno (la naguaya)': 'paratebueno',
    'patia (el bordo)': 'patia',
    'paz de ariporo (moreno)': 'paz de ariporo',
    'purace (coconuco)': 'purace',
    'roberto payan (san jose)': 'roberto payan',
    'san juan de betulia (betulia)': 'san juan de betulia',
    'san miguel (la dorada)': 'san miguel',
    'santa barbara (iscuande)': 'santa barbara',
    'santacruz (guachaves)': 'santacruz',
    'sotara (paispamba)': 'sotara',
    'tesalia (carnicerias)': 'tesalia',
    'zona bananera (sevilla)': 'zona bananera',

    # Duplicados o variantes
    'arbeleez': 'arbelaez',
    'calara': 'calarca',
    'don matias': 'donmatias',
    'cuaspud carlosama': 'cuaspud',
    'guadalajara de buga': 'buga',
    'guican de la sierra': 'guican',
    'manaure balcon del cesar (mana': 'manaure balcon del cesar',
    'palmas socorro': 'palmas del socorro',
    'pueblo rico': 'pueblorrico',
    'puerto nare (la magdalena)': 'puerto nare',
    'puerto nare-la magdalena': 'puerto nare',
    'san carlos guaroa': 'san carlos de guaroa',
    'san jose del fragua': 'san jose de fragua',
    'san pablo borbur': 'san pablo de borbur',
    'santacruz': 'santa cruz',
    'santiago de tolu': 'tolu',
    'tiquisio (pto. rico)': 'tiquisio',
    'villa de leyva': 'villa de leiva',
    'vistahermosa': 'vista hermosa',
    'yondo-casabe': 'yondo',

    # Casos truncados / incompletos
    'el canton del san pablo (man.': 'el canton del san pablo',
    'union panamericana (las animas': 'union panamericana'
}

# =========================================
# 2. Aplicar reemplazos
# =========================================

df_maestro['municipio'] = df_maestro['municipio'].replace(reemplazos_municipio)

# =========================================
# 3. Verificar resultado
# =========================================

valores_unicos_municipio = sorted(df_maestro['municipio'].dropna().unique().tolist())

print("Valores únicos en 'municipio' después de limpiar:")
for i, val in enumerate(valores_unicos_municipio, 1):
    print(f"{i}. {val}")

print(f"\nTotal de valores únicos: {len(valores_unicos_municipio)}")

Valores únicos en 'municipio' después de limpiar:
1. abejorral
2. abrego
3. abriaqui
4. acacias
5. acandi
6. acevedo
7. achi
8. agrado
9. agua de dios
10. aguachica
11. aguada
12. aguadas
13. aguazul
14. agustin codazzi
15. aipe
16. alban
17. albania
18. alcala
19. aldana
20. alejandria
21. alemania
22. algarrobo
23. algeciras
24. almaguer
25. almeida
26. alpujarra
27. altamira
28. alto baudo
29. altos del rosario
30. alvarado
31. amaga
32. amalfi
33. ambalema
34. anapoima
35. ancuya
36. andalucia
37. andes
38. angelopolis
39. angostura
40. anolaima
41. anori
42. anserma
43. ansermanuevo
44. antillas holandesas
45. antioquia
46. anza
47. anzoategui
48. apartado
49. apia
50. apulo
51. aquitania
52. aracataca
53. aranzazu
54. aratoca
55. arauca
56. arauquita
57. arbelaez
58. arboleda
59. arboledas
60. arboletes
61. arcabuco
62. arenal
63. argelia
64. argentina
65. ariguani
66. arjona
67. armenia
68. armero
69. arroyo hondo
70. aruba
71. arzerbaiyan
72. astrea
73. ataco
74. atrato
75. australia
76. austria
77. ayapel
78. bagado
79. bahia solano
80. bajo baudo
81. balboa
82. baranoa
83. baraya
84. barbacoas
85. barbosa
86. barichara
87. barranca de upia
88. barrancabermeja
89. barrancas
90. barranco de loba
91. barrancominas
92. barranquilla
93. becerril
94. belalcazar
95. belen
96. belen de los andaquies
97. belen de umbria
98. belgica
99. bello
100. belmira
101. beltran
102. berbeo
103. betania
104. beteitiva
105. betulia
106. bituima
107. boavita
108. bochalema
109. bogota
110. bojaca
111. bojaya
112. bolivar
113. bolivia
114. bosconia
115. boyaca
116. brasil
117. briceno
118. bucaramanga
119. bucarasica
120. buenaventura
121. buenavista
122. buenos aires
123. buesaco
124. buga
125. bugalagrande
126. bulgaria
127. buritica
128. busbanza
129. cabrera
130. cabuyaro
131. cacahual
132. caceres
133. cachipay
134. cachira
135. cacota
136. caicedo
137. caicedonia
138. caimito
139. cajamarca
140. cajibio
141. cajica
142. calamar
143. calarca
144. caldas
145. caldono
146. cali
147. california
148. calima
149. caloto
150. campamento
151. campo de la cruz
152. campoalegre
153. campohermoso
154. canada
155. canalete
156. canasgordas
157. candelaria
158. cantagallo
159. caparrapi
160. capitanejo
161. caqueza
162. caracoli
163. caramanta
164. carcasi
165. carepa
166. carmen de apicala
167. carmen de carupa
168. carmen de viboral
169. carmen del darien
170. carolina
171. cartagena
172. cartagena de indias
173. cartagena del chaira
174. cartago
175. caruru
176. casabianca
177. castilla la nueva
178. caucasia
179. cepita
180. cerete
181. cerinza
182. cerrito
183. cerro de san antonio
184. certegui
185. chachagui
186. chaguani
187. chalan
188. chameza
189. chaparral
190. charala
191. charta
192. chia
193. chigorodo
194. chile
195. chima
196. chimichagua
197. china republica popular
198. chinacota
199. chinavita
200. chinchina
201. chinu
202. chipaque
203. chipata
204. chiquinquira
205. chiquiza
206. chiriguana
207. chiscas
208. chita
209. chitaga
210. chitaraque
211. chivata
212. chivolo
213. chivor
214. choachi
215. choconta
216. cicuco
217. cienaga
218. cienaga de oro
219. cienega
220. cimitarra
221. circasia
222. cisneros
223. ciudad bolivar
224. clemencia
225. cocorna
226. coello
227. cogua
228. colombia
229. colon
230. coloso
231. combita
232. concepcion
233. concordia
234. condoto
235. confines
236. consaca
237. contadero
238. contratacion
239. convencion
240. copacabana
241. coper
242. cordoba
243. corea del sur
244. corinto
245. coromoro
246. corozal
247. corrales
248. costa de marfil
249. costa rica
250. cota
251. cotorra
252. covarachia
253. covenas
254. coyaima
255. cravo norte
256. cuaspud
257. cuba
258. cubara
259. cubarral
260. cucaita
261. cucunuba
262. cucuta
263. cucutilla
264. cuitiva
265. cumaral
266. cumaribo
267. cumbal
268. cumbitara
269. cunday
270. curazao
271. curillo
272. curiti
273. curumani
274. dabeiba
275. dagua
276. dibulla
277. dinamarca
278. distraccion
279. dolores
280. donmatias
281. dosquebradas
282. duitama
283. durania
284. ebejico
285. ecuador
286. egipto
287. el aguila
288. el bagre
289. el banco
290. el cairo
291. el calvario
292. el canton del san pablo
293. el carmen
294. el carmen de atrato
295. el carmen de bolivar
296. el carmen de chucuri
297. el carmen de viboral
298. el castillo
299. el cerrito
300. el charco
301. el cocuy
302. el colegio
303. el copey
304. el doncello
305. el dorado
306. el dovio
307. el encanto
308. el espino
309. el guacamayo
310. el guamo
311. el litoral del san juan
312. el molino
313. el paso
314. el paujil
315. el penol
316. el penon
317. el pinon
318. el playon
319. el reten
320. el retorno
321. el roble
322. el rosal
323. el rosario
324. el salvador
325. el santuario
326. el tablon
327. el tablon de gomez
328. el tambo
329. el tarra
330. el zulia
331. elias
332. emiratos arabes unidos
333. encino
334. enciso
335. entrerrios
336. envigado
337. espana
338. espaã‘a
339. espinal
340. estados unidos
341. facatativa
342. falan
343. filadelfia
344. filandia
345. finlandia
346. firavitoba
347. flandes
348. florencia
349. floresta
350. florian
351. florida
352. floridablanca
353. fomeque
354. fonseca
355. fortul
356. fosca
357. francia
358. francisco pizarro
359. fredonia
360. fresno
361. frontino
362. fuente de oro
363. fundacion
364. funes
365. funza
366. fuquene
367. fusagasuga
368. gachala
369. gachancipa
370. gachantiva
371. gacheta
372. galan
373. galapa
374. galeras
375. gama
376. gamarra
377. gambita
378. gameza
379. garagoa
380. garzon
381. genova
382. ghana
383. gigante
384. ginebra
385. giraldo
386. girardot
387. girardota
388. giron
389. gomez plata
390. gonzalez
391. gramalote
392. granada
393. grecia
394. guaca
395. guacamayas
396. guacari
397. guachene
398. guacheta
399. guachucal
400. guadalupe
401. guaduas
402. guaitarilla
403. gualmatan
404. guamal
405. guamo
406. guapi
407. guapota
408. guaranda
409. guarne
410. guasca
411. guatape
412. guataqui
413. guatavita
414. guatemala
415. guateque
416. guatica
417. guavata
418. guayabal de siquima
419. guayabetal
420. guayata
421. guepsa
422. guican
423. gutierrez
424. guyana
425. hacari
426. haiti
427. hatillo de loba
428. hato
429. hato corozal
430. hatonuevo
431. heliconia
432. herran
433. herveo
434. hispania
435. hobo
436. honda
437. honduras
438. hong kong (china)
439. hungria
440. ibague
441. icononzo
442. iles
443. imues
444. india
445. indonesia
446. inglaterra
447. inirida
448. inza
449. ipiales
450. iquira
451. iran
452. irlanda
453. isnos
454. israel
455. istmina
456. itagui
457. italia
458. itsmina
459. ituango
460. iza
461. jamaica
462. jambalo
463. jamundi
464. japon
465. jardin
466. jenesano
467. jerico
468. jerusalen
469. jesus maria
470. jordan
471. juan de acosta
472. junin
473. jurado
474. kenia
475. la apartada
476. la argentina
477. la belleza
478. la calera
479. la capilla
480. la ceja
481. la celia
482. la chorrera
483. la cruz
484. la cumbre
485. la dorada
486. la esperanza
487. la estrella
488. la florida
489. la gloria
490. la jagua de ibirico
491. la jagua del pilar
492. la llanada
493. la macarena
494. la merced
495. la mesa
496. la montanita
497. la palma
498. la paz
499. la pedrera
500. la pena
501. la pintada
502. la plata
503. la playa
504. la primavera
505. la salina
506. la sierra
507. la tebaida
508. la tola
509. la union
510. la uvita
511. la vega
512. la victoria
513. la virginia
514. labateca
515. labranzagrande
516. landazuri
517. lebrija
518. leiva
519. lejanias
520. lenguazaque
521. lerida
522. leticia
523. libano
524. liborina
525. linares
526. lloro
527. lopez
528. lopez de micay
529. lorica
530. los andes
531. los cordobas
532. los palmitos
533. los patios
534. los santos
535. lourdes
536. luruaco
537. luxemburgo
538. macanal
539. macaravita
540. maceo
541. macheta
542. madrid
543. magangue
544. magui
545. mahates
546. maicao
547. majagual
548. malaga
549. malambo
550. malasia
551. mallama
552. manati
553. manaure
554. manaure balcon del cesar
555. mani
556. manizales
557. manta
558. manzanares
559. mapiripan
560. margarita
561. maria la baja
562. marinilla
563. maripi
564. mariquita
565. marmato
566. marquetalia
567. marruecos
568. marsella
569. marulanda
570. matanza
571. medellin
572. medina
573. medio atrato
574. medio baudo
575. medio san juan
576. melgar
577. mercaderes
578. mesetas
579. mexico
580. milan
581. miraflores
582. miranda
583. miriti  parana
584. miriti parana
585. mistrato
586. mitu
587. mocoa
588. mogotes
589. molagavita
590. momil
591. mompos
592. mongua
593. mongui
594. moniquira
595. monitos
596. montebello
597. montecristo
598. montelibano
599. montenegro
600. monteria
601. monterrey
602. morales
603. morelia
604. morichal (papunagua)
605. morroa
606. mosquera
607. motavita
608. murillo
609. murindo
610. mutata
611. mutiscua
612. muzo
613. narino
614. nataga
615. natagaima
616. nechi
617. necocli
618. neira
619. neiva
620. nemocon
621. nicaragua
622. nigeria
623. nilo
624. nimaima
625. nobsa
626. nocaima
627. norcasia
628. norosi
629. noruega
630. novita
631. nueva antioquia
632. nueva granada
633. nueva zelandia
634. nuevo belen de bajira
635. nuevo colon
636. nunchia
637. nuqui
638. obando
639. ocamonte
640. ocana
641. oiba
642. oicata
643. olaya
644. olaya herrera
645. onzaga
646. oporapa
647. orito
648. orocue
649. ortega
650. ospina
651. otanche
652. ovejas
653. pachavita
654. pacho
655. pacoa
656. pacora
657. padilla
658. paez
659. paicol
660. pailitas
661. paime
662. paipa
663. paises bajos
664. pajarito
665. palermo
666. palestina
667. palmar
668. palmar de varela
669. palmas del socorro
670. palmira
671. palmito
672. palocabildo
673. pamplona
674. pamplonita
675. pana pana (campo alegre)
676. panama
677. pandi
678. panqueba
679. paraguay
680. paramo
681. paratebueno
682. pasca
683. pasto
684. patia
685. pauna
686. paya
687. paz de ariporo
688. paz de rio
689. pe?ol
690. pedraza
691. pelaya
692. penol
693. pensilvania
694. peque
695. pereira
696. peru
697. pesca
698. piamonte
699. piedecuesta
700. piedras
701. piendamo
702. piendamo  tunia
703. pijao
704. pijino del carmen
705. pinchote
706. pinillos
707. piojo
708. pisba
709. pisva
710. pital
711. pitalito
712. pivijay
713. planadas
714. planeta rica
715. plato
716. policarpa
717. polonia
718. polonuevo
719. ponedera
720. popayan
721. pore
722. portugal
723. potosi
724. pradera
725. prado
726. providencia
727. pueblo bello
728. pueblo nuevo
729. pueblorrico
730. puebloviejo
731. puente nacional
732. puerres
733. puerto arica
734. puerto asis
735. puerto berrio
736. puerto boyaca
737. puerto caicedo
738. puerto carreno
739. puerto colombia
740. puerto concordia
741. puerto escondido
742. puerto gaitan
743. puerto guzman
744. puerto leguizamo
745. puerto libertador
746. puerto lleras
747. puerto lopez
748. puerto nare
749. puerto narino
750. puerto parra
751. puerto rico
752. puerto rondon
753. puerto salgar
754. puerto santander
755. puerto tejada
756. puerto triunfo
757. puerto wilches
758. puli
759. pupiales
760. purace
761. purificacion
762. purisima
763. purisima de la concepcion
764. quebradanegra
765. quetame
766. quibdo
767. quimbaya
768. quinchia
769. quipama
770. quipile
771. ragonvalia
772. ramiriqui
773. raquira
774. recetor
775. regidor
776. remedios
777. remolino
778. repelon
779. republica de filipinas
780. republica de singapur
781. republica democratica alemania
782. republica dominicana
783. republica socialista de vietna
784. republica socialista devietnam
785. restrepo
786. retiro
787. ricaurte
788. rio de oro
789. rio iro
790. rio quito (paimado)
791. rio viejo
792. rioblanco
793. riofrio
794. riohacha
795. rionegro
796. riosucio
797. rioviejo
798. risaralda
799. rivera
800. roberto payan
801. roldanillo
802. roncesvalles
803. rondon
804. rosas
805. rovira
806. rumania
807. rusia
808. sabana de torres
809. sabanagrande
810. sabanalarga
811. sabanas de san angel
812. sabaneta
813. saboya
814. sacama
815. sachica
816. sahagun
817. saladoblanco
818. salamina
819. salazar
820. saldana
821. salento
822. salgar
823. samaca
824. samana
825. samaniego
826. sampues
827. san agustin
828. san alberto
829. san andres
830. san andres de cuerquia
831. san andres de sotavento
832. san andres de tumaco
833. san antero
834. san antonio
835. san antonio del tequendama
836. san benito
837. san benito abad
838. san bernardo
839. san bernardo del viento
840. san calixto
841. san carlos
842. san carlos de guaroa
843. san cayetano
844. san cristobal
845. san diego
846. san eduardo
847. san estanislao
848. san felipe
849. san fernando
850. san francisco
851. san gil
852. san jacinto
853. san jacinto del cauca
854. san jeronimo
855. san joaquin
856. san jose
857. san jose de cucuta
858. san jose de fragua
859. san jose de la montana
860. san jose de miranda
861. san jose de ocune
862. san jose de pare
863. san jose de toluviejo
864. san jose de ure
865. san jose del guaviare
866. san jose del palmar
867. san juan de arama
868. san juan de betulia
869. san juan de rioseco
870. san juan de uraba
871. san juan del cesar
872. san juan nepomuceno
873. san juanito
874. san lorenzo
875. san luis
876. san luis de gaceno
877. san luis de palenque
878. san luis de since
879. san marcos
880. san martin
881. san martin de loba
882. san martin de los llanos
883. san mateo
884. san miguel
885. san miguel de sema
886. san onofre
887. san pablo
888. san pablo de borbur
889. san pedro
890. san pedro de cartago
891. san pedro de los milagros
892. san pedro de uraba
893. san pelayo
894. san rafael
895. san roque
896. san sebastian
897. san sebastian de buenavista
898. san sebastian de mariquita
899. san vicente
900. san vicente de chucuri
901. san vicente del caguan
902. san vicente ferrer
903. san zenon
904. sandona
905. santa ana
906. santa barbara
907. santa barbara de pinto
908. santa catalina
909. santa cruz
910. santa cruz de mompox
911. santa fe de antioquia
912. santa helena del opon
913. santa isabel
914. santa lucia
915. santa maria
916. santa marta
917. santa rita
918. santa rosa
919. santa rosa de cabal
920. santa rosa de osos
921. santa rosa de viterbo
922. santa rosa del sur
923. santa rosalia
924. santa sofia
925. santacruz
926. santana
927. santander de quilichao
928. santiago
929. santo domingo
930. santo tomas
931. santuario
932. sapuyes
933. saravena
934. sardinata
935. sasaima
936. sativanorte
937. sativasur
938. segovia
939. sesquile
940. sevilla
941. siachoque
942. sibate
943. sibundoy
944. silos
945. silvania
946. silvia
947. simacota
948. simijaca
949. simiti
950. sin_dato
951. since
952. sincelejo
953. sipi
954. sitionuevo
955. soacha
956. soata
957. socha
958. socorro
959. socota
960. sogamoso
961. solano
962. soledad
963. solita
964. somondoco
965. sonson
966. sopetran
967. soplaviento
968. sopo
969. sora
970. soraca
971. sotaquira
972. sotara
973. sotara paispamba
974. suaita
975. suan
976. suarez
977. suaza
978. subachoque
979. sucre
980. sudafrica
981. suecia
982. suesca
983. suiza
984. supata
985. supia
986. surata
987. susa
988. susacon
989. sutamarchan
990. sutatausa
991. sutatenza
992. tabio
993. tado
994. tailandia
995. talaigua nuevo
996. tamalameque
997. tamara
998. tame
999. tamesis
1000. taminango
1001. tangua
1002. taraira
1003. tarapaca
1004. taraza
1005. tarqui
1006. tarso
1007. tasco
1008. tauramena
1009. tausa
1010. tello
1011. tena
1012. tenerife
1013. tenjo
1014. tenza
1015. teorama
1016. teruel
1017. tesalia
1018. tibacuy
1019. tibana
1020. tibasosa
1021. tibirita
1022. tibu
1023. tierralta
1024. timana
1025. timbio
1026. timbiqui
1027. tinjaca
1028. tipacoque
1029. tiquisio
1030. titiribi
1031. toca
1032. tocaima
1033. tocancipa
1034. togui
1035. toledo
1036. tolu
1037. toluviejo
1038. tona
1039. topaga
1040. topaipi
1041. toribio
1042. toro
1043. tota
1044. totoro
1045. trinidad
1046. trinidad y tobago
1047. trujillo
1048. tubara
1049. tuchin
1050. tulua
1051. tumaco
1052. tunja
1053. tunungua
1054. tuquerres
1055. turbaco
1056. turbana
1057. turbo
1058. turmeque
1059. turquia
1060. tuta
1061. tutasa
1062. tutaza
1063. ubala
1064. ubaque
1065. ubate
1066. ulloa
1067. umbita
1068. une
1069. unguia
1070. union panamericana
1071. uramita
1072. uribe
1073. uribia
1074. urrao
1075. uruguay
1076. urumita
1077. usiacuri
1078. utica
1079. valdivia
1080. valencia
1081. valle de san jose
1082. valle de san juan
1083. valle del guamuez (la hormiga)
1084. valledupar
1085. valparaiso
1086. vegachi
1087. velez
1088. venadillo
1089. venecia
1090. venezuela
1091. ventaquemada
1092. vergara
1093. versalles
1094. vetas
1095. viani
1096. victoria
1097. vigia del fuerte
1098. vijes
1099. villa caro
1100. villa de leiva
1101. villa de san diego de ubate
1102. villa del rosario
1103. villa rica
1104. villagarzon
1105. villagomez
1106. villahermosa
1107. villamaria
1108. villanueva
1109. villapinzon
1110. villarrica
1111. villavicencio
1112. villavieja
1113. villeta
1114. viota
1115. viracacha
1116. vista hermosa
1117. viterbo
1118. yacopi
1119. yacuanquer
1120. yaguara
1121. yali
1122. yarumal
1123. yavarate
1124. yolombo
1125. yondo
1126. yopal
1127. yotoco
1128. yugoslavia
1129. yumbo
1130. zambrano
1131. zapatoca
1132. zapayan
1133. zaragoza
1134. zarzal
1135. zetaquira
1136. zipacon
1137. zipaquira
1138. zona bananera

Total de valores únicos: 1138

In [69]:
# =========================================
# 1. Diccionario de reemplazos para 'corporacion'
# =========================================

reemplazos_corporacion = {
    'asamblea': 'asamblea departamental',
    'asamblea departamental': 'asamblea departamental',
    'concejo municipal': 'concejo',
    'concejo': 'concejo',
    'camara': 'camara',
    'camara de representantes': 'camara',
    'jal': 'jal',
    'senado': 'senado',
    'alcaldia municipal': 'alcaldia',
    'alcalde': 'alcaldia',
    'presidencia': 'presidencia',
    'gobernador': 'gobernacion',
    'consultas': 'consultas'
}

# =========================================
# 2. Aplicar reemplazos
# =========================================

df_maestro['corporacion'] = df_maestro['corporacion'].replace(reemplazos_corporacion)

# =========================================
# 3. Verificar resultado
# =========================================

valores_unicos_corporacion = df_maestro['corporacion'].dropna().unique().tolist()

print("Valores únicos en 'corporacion' después de limpiar:")
for i, val in enumerate(valores_unicos_corporacion, 1):
    print(f"{i}. {val}")

print(f"\nTotal de valores únicos: {len(valores_unicos_corporacion)}")

Valores únicos en 'corporacion' después de limpiar:
1. camara
2. presidencia
3. senado
4. asamblea departamental
5. concejo
6. alcaldia
7. jal
8. gobernacion
9. consultas

Total de valores únicos: 9

In [73]:
# Reemplazos directos en la columna 'candidato'
reemplazos_candidato = {
    'lista - mira': 'lista',
    'nuevo liberalismo - conservador -colombia justa li bres': 'lista',
    'partido nuevo liberalismo': 'lista'
}

df_maestro['candidato'] = df_maestro['candidato'].replace(reemplazos_candidato)

# Si quieres unificar cualquier valor que contenga 'lista' y una coalición adicional:
mask_lista = df_maestro['candidato'].str.contains(r'^lista\b', case=False, na=False)
df_maestro.loc[mask_lista, 'candidato'] = 'lista'

# Verificación
valores_unicos_candidato = sorted(df_maestro['candidato'].dropna().unique().tolist())
print("Total de valores únicos:", len(valores_unicos_candidato))
print(valores_unicos_candidato[:100])

Total de valores únicos: 4733
['abaned aldana lombana', 'abel alberto polanco lemos', 'abel farfan martinez', 'abel jose barrios martinez', 'abelardo duenez blanco', 'abelardo fabio morales alvarez', 'abelardo palacios gonzalez', 'abelino cardoso perdomo', 'abigail ramirez balaguera', 'abilio parada cote', 'abraham de jesus saker gonzalez', 'abraham ramirez hernandez', 'abundino rayo mahecha', 'acuerdo de coalicion partidos de la u y nuevo libe ralismo', 'adalberto lombana quintero', 'adalberto maldonado gonzalez', 'adalberto ovalle munoz', 'adalgisa rubis montero pabon', 'adela calderon arguello', 'adelaida estrella ruiz garcia', 'adelina isabel tejada mosquera', 'adelmo marulanda ruiz', 'ademir cardoso herrera', 'ader alonso anaya montesino', 'adinael contreras gonzalez', 'adolfo emilio ayala petro', 'adolfo yovanni vera', 'adonai morales ayazo', 'adrian norena gaviria', 'adrian selket jimenez lozada', 'adriana enith mora acosta', 'adriana feo zapata', 'adriana garcia garcia', 'adriana gomez marin', 'adriana isabel diaz mendoza', 'adriana janeth hernandez neira', 'adriana lucia misas arrieta', 'adriana lucia suarez suarez', 'adriana lucrecia quesada roa', 'adriana marcela gutierrez castaneda', 'adriana maria lora guerra', 'adriana maria rojas rodriguez', 'adriana maria salazar rodriguez', 'adriana maria valencia rincon', 'adriana milena garcia pino', 'adriana milena laiseca', 'adriana milena meneses rodriguez', 'adriana milena ortiz pena', 'adriana mireya nopan carlosama', 'adriana paez herrera', 'adriana ramirez leon', 'adriana stella hernandez', 'agustin duval ortega criollo', 'agustin francisco villarreal gonzalez', 'agustin gil morales', 'agustin lopez ariza', 'agustina sinisterra', 'aida del carmen otero urzola', 'aidee garcia granja', 'alan castano escobar', 'alan farid barrios vega', 'alan rene miranda felix', 'alaris alarieth brito ortiz', 'alba delia yepes ortiz', 'alba esther cervera espejo', 'alba leonor valdes parra', 'alba libia loaiza henao', 'alba liceth masmela tachack', 'alba lucia lamus martinez', 'alba luz gomez gomez', 'alba luz linares morales', 'alba milena narvaez gomez', 'alba nubia gonzalez bernal', 'alba nubia moreno gaviria', 'alba patricia diaz penaranda', 'alba sofia macias ibanez', 'alba viviana lopez cabrera', 'albeiro antonio garcia gonzalez', 'albert john valdeblanquez jimenez', 'alberto bustos leon', 'alberto cardona orozco', 'alberto fernandez bustamante', 'alberto martinez francisco', 'alberto ovidio munoz pabon', 'alberto pelaez henao', 'alberto torres caro', 'alberto uribe mejia', 'alberto villamizar cardenas', 'alcides ospina trujillo', 'aldemar becerra zuluaga', 'aldemar lopez caceres', 'aldemar ruiz lozano', 'aldemar velez espanol', 'aldo andres duval martinez', 'aleida godoy velasquez', 'aleida montano carrillo', 'alejandra correa quintero', 'alejandra de los angeles redondo caraballo', 'alejandra maria martinez guerrero', 'alejandra marin gallo']

In [77]:
import pandas as pd

# Asegurar tipos consistentes
df_maestro['ano'] = pd.to_numeric(df_maestro['ano'], errors='coerce')
df_maestro['coddpto'] = df_maestro['coddpto'].astype(str).str.strip()
df_maestro['codmpio'] = df_maestro['codmpio'].astype(str).str.strip()
df_maestro['departamento'] = df_maestro['departamento'].astype(str).str.strip()
df_maestro['municipio'] = df_maestro['municipio'].astype(str).str.strip()

# Crear clave territorial
df_maestro['clave_territorial'] = (
    df_maestro['coddpto'] + '-' + df_maestro['codmpio']
)

# Ver cuántas combinaciones únicas hay por año
resumen_anual = (
    df_maestro
    .groupby('ano', dropna=False)
    .agg(
        registros=('clave_territorial', 'size'),
        claves_unicas=('clave_territorial', 'nunique'),
        deptos_unicos=('coddpto', 'nunique'),
        municipios_unicos=('codmpio', 'nunique')
    )
    .reset_index()
    .sort_values('ano')
)

print("Resumen por año:")
print(resumen_anual)

# Detectar claves territoriales que cambian de nombre según el año
cambios_territoriales = (
    df_maestro
    .groupby('clave_territorial')
    .agg(
        anios=('ano', lambda x: sorted(pd.Series(x).dropna().unique().tolist())),
        departamentos=('departamento', lambda x: sorted(pd.Series(x).dropna().unique().tolist())),
        municipios=('municipio', lambda x: sorted(pd.Series(x).dropna().unique().tolist()))
    )
    .reset_index()
)

# Quedarse con las claves que tienen más de una forma de nombre o aparecen en varios años
cambios_territoriales = cambios_territoriales[
    (cambios_territoriales['anios'].apply(len) > 1) |
    (cambios_territoriales['departamentos'].apply(len) > 1) |
    (cambios_territoriales['municipios'].apply(len) > 1)
].sort_values('clave_territorial')

print("\nClaves territoriales con cambios de nombre o presencia en varios años:")
print(cambios_territoriales.head(50))

# Exportar revisión
resumen_anual.to_csv('output/resumen_anual_codigos.csv', index=False)
cambios_territoriales.to_csv('output/cambios_territoriales.csv', index=False)

Resumen por año:
    ano  registros  claves_unicas  deptos_unicos  municipios_unicos
0  1982       1342           1062             34               1060
1  1986      10612           1057             27               1019
2  1988       2188            678             17                678
3  2022     188414           1165             34                304
4  2023     695629            628             31                212
5  2026     194179           1055             32                294

Claves territoriales con cambios de nombre o presencia en varios años:
   clave_territorial         anios departamentos       municipios
0                1-1  [2022, 2023]   [antioquia]       [medellin]
1               1-10  [2022, 2023]   [antioquia]     [alejandria]
3              1-103  [2022, 2023]   [antioquia]     [copacabana]
4              1-106  [2022, 2023]   [antioquia]      [chigorodo]
5              1-109  [2022, 2023]   [antioquia]        [dabeiba]
8              1-117  [2022, 2023]   [antioquia]       [el bagre]
10             1-121  [2022, 2023]   [antioquia]       [envigado]
11             1-124  [2022, 2023]   [antioquia]       [fredonia]
12             1-127  [2022, 2023]   [antioquia]       [frontino]
14             1-130  [2022, 2023]   [antioquia]        [giraldo]
15             1-133  [2022, 2023]   [antioquia]      [girardota]
19             1-142  [2022, 2023]   [antioquia]         [guarne]
20             1-145  [2022, 2023]   [antioquia]        [guatape]
23             1-151  [2022, 2023]   [antioquia]         [itagui]
24             1-154  [2022, 2023]   [antioquia]        [ituango]
25             1-157  [2022, 2023]   [antioquia]         [jardin]
26              1-16  [2022, 2023]   [antioquia]         [amalfi]
28             1-163  [2022, 2023]   [antioquia]        [la ceja]
29             1-166  [2022, 2023]   [antioquia]    [la estrella]
30             1-168  [2022, 2023]   [antioquia]    [puerto nare]
31             1-169  [2022, 2023]   [antioquia]       [la union]
32             1-170  [2022, 2023]   [antioquia]     [la pintada]
34             1-175  [2022, 2023]   [antioquia]          [maceo]
36             1-181  [2022, 2023]   [antioquia]     [montebello]
39              1-19  [2022, 2023]   [antioquia]          [andes]
40             1-190  [2022, 2023]   [antioquia]         [narino]
42             1-192  [2022, 2023]   [antioquia]        [necocli]
45             1-199  [2022, 2023]   [antioquia]          [peque]
46             1-202  [2022, 2023]   [antioquia]    [pueblorrico]
47             1-205  [2022, 2023]   [antioquia]  [puerto berrio]
49             1-208  [2022, 2023]   [antioquia]       [remedios]
50             1-211  [2022, 2023]   [antioquia]         [retiro]
51             1-214  [2022, 2023]   [antioquia]       [rionegro]
53             1-218  [2022, 2023]   [antioquia]       [sabaneta]
57             1-226  [2022, 2023]   [antioquia]     [san carlos]
59             1-229  [2022, 2023]   [antioquia]   [san jeronimo]
62             1-232  [2022, 2023]   [antioquia]       [san luis]
63             1-235  [2022, 2023]   [antioquia]      [san pedro]
65             1-238  [2022, 2023]   [antioquia]     [san rafael]
68             1-247  [2022, 2023]   [antioquia]  [santa barbara]
73             1-259  [2022, 2023]   [antioquia]        [segovia]
78             1-271  [2022, 2023]   [antioquia]          [tarso]
81              1-28  [2022, 2023]   [antioquia]          [anori]
82             1-280  [2022, 2023]   [antioquia]          [turbo]
84             1-283  [2022, 2023]   [antioquia]          [urrao]
88             1-292  [2022, 2023]   [antioquia]        [venecia]
89             1-293  [2022, 2023]   [antioquia]           [yali]
90             1-295  [2022, 2023]   [antioquia]        [yarumal]
91             1-298  [2022, 2023]   [antioquia]        [yolombo]
94              1-31  [2022, 2023]   [antioquia]      [antioquia]

In [72]:
df_maestro_sql.to_csv(r"C:\Users\qluis\Documents\Proyectos\Nuevo liberalismo\output\df_maestro_candidatos.csv", index=False, encoding="utf-8-sig")

In [70]:
# Obtener valores únicos de la columna 'candidato'
valores_unicos_candidato = sorted(df_maestro['candidato'].dropna().unique().tolist())

print("Valores únicos en 'candidato':")
for i, val in enumerate(valores_unicos_candidato, 1):
    print(f"{i}. {val}")

print(f"\nTotal de valores únicos: {len(valores_unicos_candidato)}")

Valores únicos en 'candidato':
1. abaned aldana lombana
2. abel alberto polanco lemos
3. abel farfan martinez
4. abel jose barrios martinez
5. abelardo duenez blanco
6. abelardo fabio morales alvarez
7. abelardo palacios gonzalez
8. abelino cardoso perdomo
9. abigail ramirez balaguera
10. abilio parada cote
11. abraham de jesus saker gonzalez
12. abraham ramirez hernandez
13. abundino rayo mahecha
14. acuerdo de coalicion partidos de la u y nuevo libe ralismo
15. adalberto lombana quintero
16. adalberto maldonado gonzalez
17. adalberto ovalle munoz
18. adalgisa rubis montero pabon
19. adela calderon arguello
20. adelaida estrella ruiz garcia
21. adelina isabel tejada mosquera
22. adelmo marulanda ruiz
23. ademir cardoso herrera
24. ader alonso anaya montesino
25. adinael contreras gonzalez
26. adolfo emilio ayala petro
27. adolfo yovanni vera
28. adonai morales ayazo
29. adrian norena gaviria
30. adrian selket jimenez lozada
31. adriana enith mora acosta
32. adriana feo zapata
33. adriana garcia garcia
34. adriana gomez marin
35. adriana isabel diaz mendoza
36. adriana janeth hernandez neira
37. adriana lucia misas arrieta
38. adriana lucia suarez suarez
39. adriana lucrecia quesada roa
40. adriana marcela gutierrez castaneda
41. adriana maria lora guerra
42. adriana maria rojas rodriguez
43. adriana maria salazar rodriguez
44. adriana maria valencia rincon
45. adriana milena garcia pino
46. adriana milena laiseca
47. adriana milena meneses rodriguez
48. adriana milena ortiz pena
49. adriana mireya nopan carlosama
50. adriana paez herrera
51. adriana ramirez leon
52. adriana stella hernandez
53. agustin duval ortega criollo
54. agustin francisco villarreal gonzalez
55. agustin gil morales
56. agustin lopez ariza
57. agustina sinisterra
58. aida del carmen otero urzola
59. aidee garcia granja
60. alan castano escobar
61. alan farid barrios vega
62. alan rene miranda felix
63. alaris alarieth brito ortiz
64. alba delia yepes ortiz
65. alba esther cervera espejo
66. alba leonor valdes parra
67. alba libia loaiza henao
68. alba liceth masmela tachack
69. alba lucia lamus martinez
70. alba luz gomez gomez
71. alba luz linares morales
72. alba milena narvaez gomez
73. alba nubia gonzalez bernal
74. alba nubia moreno gaviria
75. alba patricia diaz penaranda
76. alba sofia macias ibanez
77. alba viviana lopez cabrera
78. albeiro antonio garcia gonzalez
79. albert john valdeblanquez jimenez
80. alberto bustos leon
81. alberto cardona orozco
82. alberto fernandez bustamante
83. alberto martinez francisco
84. alberto ovidio munoz pabon
85. alberto pelaez henao
86. alberto torres caro
87. alberto uribe mejia
88. alberto villamizar cardenas
89. alcides ospina trujillo
90. aldemar becerra zuluaga
91. aldemar lopez caceres
92. aldemar ruiz lozano
93. aldemar velez espanol
94. aldo andres duval martinez
95. aleida godoy velasquez
96. aleida montano carrillo
97. alejandra correa quintero
98. alejandra de los angeles redondo caraballo
99. alejandra maria martinez guerrero
100. alejandra marin gallo
101. alejandrino canon ortiz
102. alejandro almeida rueda
103. alejandro campino ramirez
104. alejandro castaneda estrada
105. alejandro enrique mercado rojano
106. alejandro mina velez
107. alejandro nicolas salazar narvaez
108. alejandro restrepo gomez
109. alex alberto fernandez harding
110. alex ferney gonzalez cumanaica
111. alex jair sanchez bareno
112. alex nasayo yucuma
113. alexa lucia peinado mejia
114. alexander alarcon cordoba
115. alexander arias fernandez
116. alexander bram martinez
117. alexander cardenas merchan
118. alexander castaneda devia
119. alexander celedon ramos
120. alexander daza galindo
121. alexander de jesus chavarria montoya
122. alexander dulcey lopez
123. alexander eliecer cerpa castro
124. alexander ernesto triana henao
125. alexander espitia reyes
126. alexander galvis ramirez
127. alexander godoy gutierrez
128. alexander gonzalez avila
129. alexander guinea
130. alexander gutierrez castellanos
131. alexander icabuco velasquez
132. alexander jose guette guette
133. alexander laguna reyes
134. alexander mina mancilla
135. alexander quemba garcia
136. alexander rafael anillo borda
137. alexander rafael ebrath martinez
138. alexander saenz mora
139. alexander salazar chinchajoa
140. alexander ulloa cortes
141. alexandra maria acuna vega
142. alexandra maria castrillon higuera
143. alexandra medina charry
144. alexandra sierra beltran
145. alexandra tordecilla silgado
146. alexandra yulieth arevalo gonzalez
147. alexi lopez brochero
148. alexis ascanio arenas
149. aleyda lucia ramirez velasquez
150. alfonso jaramillo bravo
151. alfonso londono vallejo
152. alfonso manuel palencia osorio
153. alfonso montoya zapata
154. alfonso sotelo chacon
155. alfredo althviz ramirez
156. alfredo baza jimenez
157. alfredo jose gomez ceballo
158. alfredo lopez
159. alfredy antonio utria buendia
160. ali mustapha el zoghbi
161. alice del carmen nunez gomez
162. alicia de carmen rodriguez salcedo
163. alicia maria ocampo bedoya
164. alinson gomez vente
165. alirio andres delgado canizares
166. alirio antonio monsalve moreno
167. alirio bohorquez romero
168. alirio marin
169. alix lorena ordonez martinez
170. alma teresa gonzalez morales
171. almir jose almanza perez
172. alonso alexander cifuentes hoya
173. alonso olarte rueda
174. alonso palacio velasquez
175. alsira paola cortina herrera
176. alvaro alirio espitia murcia
177. alvaro antonio trujillo quintana
178. alvaro arteaga valencia
179. alvaro de jesus gil vasquez
180. alvaro german villacis coral
181. alvaro guevara montoya
182. alvaro hernan pulgarin diez
183. alvaro humberto montoya cruz
184. alvaro javier pava castaneda
185. alvaro javier tobar mendoza
186. alvaro jose cuaran mejia
187. alvaro jose lara meza
188. alvaro jose machuca oliveros
189. alvaro jose martinez suarez
190. alvaro jose pardo montes
191. alvaro jose sanchez alvarez
192. alvaro luis ariza villadiego
193. alvaro marulanda calixto
194. alvaro rene meneses cepeda
195. alvaro ruben osorio ortega
196. alvaro rueda sanchez
197. alveiro lopez ospina
198. amada maria torres herrera
199. amadid suarez martinez
200. amalia andrade mesa
201. amanda bernal florido
202. amanda jose fuentes contreras
203. amders lozano martinez
204. amed jose zawady pupo
205. amilvia esther ariza mejia
206. aminelsi franco quiroz
207. amparo cordero figueroa
208. amparo de jesus espitia guzman
209. amparo delgado ayala
210. amparo guaza gonzalez
211. amparo villamil novoa
212. ana aurora mendoza garcia
213. ana carolina chamorro munoz
214. ana cecilia baron santisteban
215. ana cristina luna anaya
216. ana del carmen ramirez martinez
217. ana dionicia vega torres
218. ana doris mosquera agualimpia
219. ana emilce tarazona hernandez
220. ana esperanza alzate alzate
221. ana felix valencia moreno
222. ana francisca suarez gomez
223. ana iris guerrero morales
224. ana isabel arango alcaraz
225. ana isabel correa zuleta
226. ana isabel gonzalez rodriguez
227. ana isabel hernandez reyes
228. ana isabel uribe londono
229. ana joaquina gonzalez bermudez
230. ana judit mayo simanca
231. ana julieth pena duarte
232. ana leonor vanegas rojas
233. ana luisa rodriguez cruzco
234. ana marcela davila arias
235. ana marcela gutierrez maturana
236. ana maria alvarez aguilar
237. ana maria lopez escobar
238. ana maria medina vanegas
239. ana maria orozco velez
240. ana maria osorio morales
241. ana maria perez guachavez
242. ana maria ramirez rodriguez
243. ana marlen hernandez yanquen
244. ana milena german soto
245. ana milena gonzalez martinez
246. ana milena sucerquia adarve
247. ana milena urian martinez
248. ana rita goyeneche leal
249. ana rosa balanta cabezas
250. ana rubiela valencia hincapie
251. ana victoria beltran ramirez
252. ana yolima hernandez pico
253. ana yurely leon rueda
254. analy santofimio aparicio
255. ancelmo monroy curvelo
256. anderson escobar santander
257. anderson ivan benavidez cardozo
258. anderson osorno gomez
259. anderson portilla parada
260. anderson riano leon
261. andrea alejandra montenegro ochoa
262. andrea carolina duran moreno
263. andrea del pilar diaz virguez
264. andrea johanna gomez arias
265. andrea liliana gomez giraldo
266. andrea lineth ceron tique
267. andrea lizeth quintana padilla
268. andrea lorena diaz eraso
269. andrea tatiana alhucema ordonez
270. andres alberto fajardo munoz
271. andres camilo acevedo barragan
272. andres camilo ramirez zorro
273. andres camilo rodriguez villamizar
274. andres david narvaez alquerque
275. andres de jesus ruiz diaz
276. andres devia gordillo
277. andres felipe ardila vega
278. andres felipe barandica rudas
279. andres felipe bautista vera
280. andres felipe forero rojas
281. andres felipe oviedo guerra
282. andres felipe perez alaix
283. andres felipe porras acero
284. andres felipe porras piraquive
285. andres felipe rojas rayo
286. andres felipe villa oyola
287. andres fernando gomez bermudez
288. andres fidalgo ruiz castaneda
289. andres giovanny holguin pineros
290. andres giraldo velasquez
291. andres hincapie rendon
292. andres ivan zuluaga zapata
293. andres javier ayos garcia
294. andres jeronimo de la cruz diaz
295. andres jose mendoza marmol
296. andres josue bohorquez perez
297. andres manuel plata quintero
298. andres mauricio aricapa restrepo
299. andres mauricio diaz arias
300. andres mauricio prieto sanchez
301. andres mauricio sanchez orozco
302. andres orlando vera rodriguez
303. andres paez moreno
304. andres prieto mendez
305. andres sarralde delgado
306. andros lionith buitrago lopez
307. aneiro leon leon
308. aneth palencia paz
309. angel antonio forero ramirez
310. angel custodio fuentes jimenez
311. angel david acosta castilla
312. angel de jesus villada
313. angel enrique perez contreras
314. angel maria perez jimenez
315. angel martin ayala pena
316. angel miguel cala calderon
317. angel porfirio alcaraz moreno
318. angel simon cruz herrera
319. angel victorio zuniga ibarguen
320. angela marcela josa vallejo
321. angela maria daza cardenas
322. angela maria lopez pardo
323. angela maria perez mahecha
324. angela stephanie polo rodriguez
325. angela viviana hernandez acosta
326. angelberto garcia hernandez
327. angelica maria canaval sanchez
328. angelica maria hernandez riano
329. angelica maria pineros duque
330. angelica maria suarez alvarez
331. angelica paola ariza rivera
332. angelie sofia renteria palencia
333. angelo florez jaramillo
334. angely fonseca cadena
335. angi paola perdomo trujillo
336. angie aztrit rios montoya
337. angie carolina arias pette
338. angie daniela mamian sanchez
339. angie katerine pena moreno
340. angie katherine martinez chacon
341. angie katherinne hernandez velasquez
342. angie liceth cerezo reyes
343. angie lorena bonilla rios
344. angie paola herrera perez
345. angie tatiana jaque piraban
346. angie valentina mesa tello
347. angie viviana ostos achuri
348. angui lorena mendoza mesa
349. anibal abraham davila bracamonte
350. anirley julio viloria
351. anita lievano toledo
352. antonio de los reyes pacheco ramos
353. antonio emiro noriega ochoa
354. antonio j lizarazo ocampo
355. antonio javier grueso quinones
356. antonio jose berrio ortega
357. antonio jose giraldo henao
358. antonio jose guzman otalvaro
359. antonio jose oviedo acosta
360. antonio julio julio peralta
361. antonio lagares norato
362. antonio lizarazo ocampo
363. antonio miguel arevalo orozco
364. antonio miguel herrera morales
365. antonio montano orobio
366. anuar jose jimenez quintero
367. anyela alexandra guerrero pacheco
368. anyely marcela antequera oliva
369. anyerli enrique coronado luquez
370. anyi jhoana gutierrez pidiachi
371. anyi vanessa martinez jimenez
372. anyi yulidtza rodriguez ariza
373. anyis paola melgarejo cueto
374. apolonio teran rodriguez
375. aquilino avila ferreira
376. aracelia mateus ruiz
377. aracelis del carmen morelo hernandez
378. aracelis morales acuna
379. arbey garcia ospina
380. arbey portocarrero carabali
381. arcangel cardenas luna
382. arcenio de jesus yarce garcia
383. arelis elvira rodriguez serrano
384. arelys marina sanjuan gomez
385. argemiro figueredo torres
386. argemiro rojas ortiz
387. argemiro teatin cely
388. argenida de la rosa valencia
389. ariel andres rodriguez hernandez
390. arifa del socorro rincon rodriguez
391. arismendi mora perdomo
392. aristides antonio gonzalez sanchez
393. arlett maria blanco escalante
394. arley fabian salazar cuellar
395. arley fernando sanchez orozco
396. armando amaris arteaga
397. armando correa marin
398. armando daza ariza
399. armando enrique rocha arrieta
400. armando gomez camayo
401. armando gonzalez murillo
402. armando guiza barrera
403. armando munoz ramirez
404. armando rafael orozco cantillo
405. arnaldo hoyos tribino
406. arnaldo lissandro cortes rodriguez
407. arnold mauricio perea perea
408. arnoldo prada monsalve
409. arnolfo de jesus montoya gutierrez
410. arnuel bedoya aldana
411. arnulfo gavidia cardenas
412. arnulfo pineda trivino
413. arquimedes cetina panqueva
414. arquinson duvan pava alzate
415. arturo serabia better
416. ary fredy sanchez prieto
417. asdrubal bareno camuan
418. asenet emilsen parra cardona
419. asmed carrillo mesino
420. astrid carolina uribe barrios
421. astrid elena ramirez cuervo
422. audelia forero meche
423. audisnel corcho gonzalez
424. audith bibiana osorio villadiego
425. augusto fabio avendano cervantes
426. augusto fernando oviedo rodriguez
427. aura carolina daza orozco
428. aura cristina criollo portela
429. aura esther dominguez cubaque
430. aura patricia pastas narvaez
431. aura rosana padilla trivino
432. aury stella zurita sinning
433. ayda luz gomez oliveros
434. bairon andres zapata rojo
435. bairon leonel carrascal leguizamo
436. banesa paola de avila varela
437. bartolo guzman lopez
438. bartolome gomez sanchez
439. bayron gabriel cruz iguad
440. bayron lozano sanchez
441. beatriz elena gaviria villa
442. beatriz elena perez hernandez
443. beatriz eugenia satizabal quintana
444. beatriz stella severiche bustamante
445. belcy yohana ceron castillo
446. belen lucia caro varela
447. belizario itanare chipiaje
448. belkis jose arrieta gutierrez
449. belkis licet hernandez hernandez
450. belky paola ramos rivera
451. bella nery lopez vargas
452. belly jhuliana suarez reyes
453. belmer jose caraballo castro
454. benito alfonso florez araque
455. benito almeida penaloza
456. benito lopez borrero
457. benjamin chona chona
458. benjamin edrey rey batista
459. benjamin fernando villa ramirez
460. benjamin lara gonzalez
461. berenice sandoval jaimez
462. bernardino aguilar ayala
463. bernardino antonio mejia menases
464. bernardo andres ramos fandino
465. bernardo manuel ortiz vasquez
466. bernardo patino loaiza
467. bersy marcela gonzalez romero
468. bertha cecilia restrepo arenas
469. bertha tulia gonzalez gaviria
470. betsy paola gualdron cahuenos
471. bibiana patricia ortega vasquez
472. bibiana quintero isaza
473. bibiana rodriguez rozo
474. blanca alicia cardenas mier
475. blanca aurora usaquen rincon
476. blanca marina rosas
477. blanca nidia castro herrera
478. blanca orfilia lopez cadavid
479. blanca rocio velasco
480. blanca rosa manrique mejia
481. bleider de jesus avila polanco
482. boris alfredo mardach torres
483. brayan andres blanco rios
484. brayan andres mendoza giraldo
485. brayan david salazar herrera
486. brayan mauricio ramirez munoz
487. brayan steven rojas munoz
488. brenda charry lasso
489. brenda joanna henao ramirez
490. brenda karina bohorquez diaz
491. brenda luz cabarcas gomez
492. breyner rafael lozano polanco
493. briggitte tatiana garcia renteria
494. brigida ardila arenas
495. brineth andrea zamorano navarro
496. bruno jose briasco rosado
497. bryan alberto cano vasquez
498. bryan alexis amaya sanchez
499. bryan jose duarte lazcano
500. brysbany dayana narcisa juajibioy dejoy
501. buenaventura quintero malaver
502. calet perez acosta
503. camila andrea jaramillo ortiz
504. camilo alexander castro velandia
505. camilo alexis galvis acevedo
506. camilo andres astaiza puerta
507. camilo andres canon vega
508. camilo andres cuchumbe coronado
509. camilo andres munevar poveda
510. camilo andres pereira castro
511. camilo andres salas barreto
512. camilo andres salgado camacho
513. camilo andres vela forero
514. camilo antonio polo pertuz
515. camilo antonio suarez ramirez
516. camilo barrera toro
517. camilo ernesto santamaria
518. campo elias ramirez yanez
519. candelaria del carmen bastidas martinez
520. candelaria judith fontalvo pizarro
521. candelaria rosa hernandez perez
522. candy maria pinto paez
523. caren yasmin tarapues urbano
524. carlo magno ballesteros contreras
525. carlos albeiro restrepo osorno
526. carlos alberto acevedo osorio
527. carlos alberto arango lopez
528. carlos alberto atencio rodriguez
529. carlos alberto bautista martinez
530. carlos alberto bermudez tangarife
531. carlos alberto cabrera salazar
532. carlos alberto castro sanchez
533. carlos alberto cuadros alvear
534. carlos alberto de la hoz fontalvo
535. carlos alberto gil pineda
536. carlos alberto guerra morales
537. carlos alberto holguin
538. carlos alberto jaramillo bernal
539. carlos alberto marin henao
540. carlos alberto monterrosa lominet
541. carlos alberto nieto martinez
542. carlos alberto perafan revelo
543. carlos alberto perez molina
544. carlos alberto perez velasquez
545. carlos alberto rivera colina
546. carlos alberto robayo rey
547. carlos alberto rojas maldonado
548. carlos alberto romero martinez
549. carlos alberto sanchez diossa
550. carlos alberto sanchez genes
551. carlos alberto sanchez suarez
552. carlos alberto soto cuellar
553. carlos alberto zarate guio
554. carlos alejandro porras melgarejo
555. carlos alexander marino salgado
556. carlos alfonso becerra alvarez
557. carlos alfonso lopez parra
558. carlos alfonso minu
559. carlos alfredo dehaquiz infante
560. carlos alfredo maya montenegro
561. carlos andres acosta santacruz
562. carlos andres benavides pena
563. carlos andres benavides reyes
564. carlos andres bernal alvarez
565. carlos andres cardona hoyos
566. carlos andres contreras garcia
567. carlos andres fajardo guzman
568. carlos andres fidel vicente jaramillo pombo
569. carlos andres pelaez rave
570. carlos andres perea ibarguen
571. carlos andres rincon garcia
572. carlos antonio martinez vega
573. carlos ardila ballesteros
574. carlos arturo castaneda hernandez
575. carlos arturo franco montoya
576. carlos arturo guevara villacorte
577. carlos arturo higuita vargas
578. carlos arturo martinez restrepo
579. carlos arturo monsalve caldera
580. carlos arturo montenegro mora
581. carlos arturo ramirez corzo
582. carlos augusto arango llanos
583. carlos augusto cervantes navarro
584. carlos augusto escobar anzola
585. carlos augusto hermocilla gracia
586. carlos augusto hernandez jimenez
587. carlos augusto rozo devia
588. carlos baez monsalve
589. carlos bernardo rivera jauregui
590. carlos cesar bonett villamil
591. carlos daniel aristizabal borja
592. carlos daniel rueda quintero
593. carlos daniel zamora zapata
594. carlos david estupinan hurtado
595. carlos drews castro
596. carlos eduardo cruz cantillo
597. carlos eduardo olmos novoa
598. carlos eduardo rayo pineda
599. carlos eduardo restrepo garcia
600. carlos eduardo tarazona sandoval
601. carlos eduardo vesga gomez
602. carlos emilio chaves mora
603. carlos emilio marquez osorio
604. carlos emilio montoya bermudez
605. carlos enrique arango perez
606. carlos enrique de jesus feliz monsalve
607. carlos enrique mira rojas
608. carlos enrique rico mendoza
609. carlos esteban perez velez
610. carlos felipe sarmiento rojas
611. carlos fernando dorado goyes
612. carlos fernando galan pachon
613. carlos gilberto romero parrado
614. carlos harbey rodriguez rojas
615. carlos herrera fajardo
616. carlos jose de la hoz navarro
617. carlos jose ortiz espitia
618. carlos julio alvarez prieto
619. carlos julio bolivar rubiano
620. carlos julio castaneda arango

In [76]:
import duckdb

query_sql = """
SELECT DISTINCT (codmpio)
FROM 
    df_maestro

"""

# Ejecutar la consulta y convertir el resultado a un nuevo DataFrame
df_maestro_sql = duckdb.sql(query_sql).df()
df_maestro_sql.head(100)

    codmpio
0     50318
1      5040
2      5044
3      5051
4      5059
..      ...
95      198
96       17
97      360
98      135
99      500

[100 rows x 1 columns]

In [78]:
import pandas as pd

# Normalizar tipos
for col in ['departamento', 'municipio', 'coddpto', 'codmpio']:
    df_maestro[col] = df_maestro[col].astype(str).str.strip()

# Quitar posibles nulos codificados como 'nan'
df_chk = df_maestro.copy()
df_chk = df_chk[~df_chk['departamento'].isin(['nan', 'None', ''])].copy()
df_chk = df_chk[~df_chk['municipio'].isin(['nan', 'None', ''])].copy()
df_chk = df_chk[~df_chk['coddpto'].isin(['nan', 'None', ''])].copy()
df_chk = df_chk[~df_chk['codmpio'].isin(['nan', 'None', ''])].copy()

# 1) Para cada (departamento, municipio), cuántos códigos distintos hay
codigos_por_nombre = (
    df_chk.groupby(['departamento', 'municipio'], dropna=False)
    .agg(
        coddpto_unicos=('coddpto', 'nunique'),
        codmpio_unicos=('codmpio', 'nunique'),
        registros=('municipio', 'size')
    )
    .reset_index()
)

# Casos problemáticos: más de un código para el mismo nombre
problemas_nombre = codigos_por_nombre[
    (codigos_por_nombre['coddpto_unicos'] > 1) |
    (codigos_por_nombre['codmpio_unicos'] > 1)
].sort_values(['departamento', 'municipio'])

print("Casos donde un mismo nombre tiene más de un código:")
print(problemas_nombre.head(200))
print("\nTotal de casos problemáticos:", len(problemas_nombre))

# 2) Para cada código, cuántos nombres distintos hay
nombres_por_codigo = (
    df_chk.groupby(['coddpto', 'codmpio'], dropna=False)
    .agg(
        departamentos_unicos=('departamento', 'nunique'),
        municipios_unicos=('municipio', 'nunique'),
        registros=('municipio', 'size')
    )
    .reset_index()
)

# Casos problemáticos: un mismo código asociado a más de un nombre
problemas_codigo = nombres_por_codigo[
    (nombres_por_codigo['departamentos_unicos'] > 1) |
    (nombres_por_codigo['municipios_unicos'] > 1)
].sort_values(['coddpto', 'codmpio'])

print("\nCasos donde un mismo código tiene más de un nombre:")
print(problemas_codigo.head(200))
print("\nTotal de casos problemáticos por código:", len(problemas_codigo))

# Exportar resultados
problemas_nombre.to_csv('output/problemas_nombre_vs_codigo.csv', index=False)
problemas_codigo.to_csv('output/problemas_codigo_vs_nombre.csv', index=False)
codigos_por_nombre.to_csv('output/codigos_por_nombre.csv', index=False)
nombres_por_codigo.to_csv('output/nombres_por_codigo.csv', index=False)

Casos donde un mismo nombre tiene más de un código:
    departamento      municipio  coddpto_unicos  codmpio_unicos  registros
0       amazonas     el encanto               2               2          7
1       amazonas    la chorrera               2               2          4
4       amazonas        leticia               2               2        289
8       amazonas  puerto narino               2               2         32
11     antioquia      abejorral               2               2         36
..           ...            ...             ...             ...        ...
237       boyaca        briceno               2               2         69
238       boyaca     buenavista               2               2        152
239       boyaca       busbanza               2               2         40
240       boyaca         caldas               2               2        207
241       boyaca   campohermoso               2               2         95

[200 rows x 5 columns]

Total de casos problemáticos: 1062

Casos donde un mismo código tiene más de un nombre:
     coddpto codmpio  departamentos_unicos  municipios_unicos  registros
195       13   13001                     1                  2          8
207       13   13468                     1                  2          8
350       15   15550                     1                  2         12
396       15   15839                     1                  2         12
489       15   85001                     2                  1          4
490       15   85010                     2                  1          4
491       15   85015                     2                  1          4
492       15   85125                     2                  1          4
493       15   85136                     2                  1          4
494       15   85139                     2                  1          4
495       15   85162                     2                  1          4
496       15   85225                     2                  1          4
497       15   85230                     2                  1          4
498       15   85250                     2                  1          4
499       15   85263                     2                  1          4
500       15   85279                     2                  1          4
501       15   85300                     2                  1          4
503       15   85325                     2                  1          4
504       15   85400                     2                  1          4
505       15   85410                     2                  1          4
506       15   85430                     2                  1          4
507       15   85440                     2                  1          4
611       19   19418                     1                  2         12
618       19   19548                     1                  2         12
626       19   19760                     1                  2         12
761       23   23586                     1                  2         14
824       25   11001                     2                  1         26
934       25   25843                     1                  2         27
1054      27   27245                     1                  2         10
1055      27   27361                     1                  2         10
1396       5    5042                     1                  2         17
1407       5    5101                     1                  2         17
1418       5    5148                     1                  2         17
1474       5    5647                     1                  2         17
1481       5    5664                     1                  2         17
1485       5    5674                     1                  2         17
1652      52   52835                     1                  2          8
1675      54   54001                     1                  2         16
1999      70   70742                     1                  2         10
2002      70   70823                     1                  2         10
2032      73   73443                     1                  2         10
2179      88     355                     1                  2       1454
2214      88     690                     1                  2          4
2324      99   99496                     1                  2          3
2329      99   99760                     1                  2          3

Total de casos problemáticos por código: 45

In [79]:
import pandas as pd
import numpy as np
import unicodedata
import re

# df_maestro: dataframe original
df = df_maestro.copy()

def norm_text(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip().lower()
    x = unicodedata.normalize('NFKD', x).encode('ascii', 'ignore').decode('utf-8')
    x = re.sub(r'[^a-z0-9\s]', ' ', x)
    x = re.sub(r'\s+', ' ', x).strip()
    return x

# Normalización básica
df['ano'] = pd.to_numeric(df['ano'], errors='coerce')
for col in ['departamento', 'municipio', 'coddpto', 'codmpio']:
    df[col] = df[col].astype(str).str.strip()

df['departamento_norm'] = df['departamento'].map(norm_text)
df['municipio_norm'] = df['municipio'].map(norm_text)

# Filtrar filas utilizables
valid = df[
    df['departamento_norm'].notna() &
    df['municipio_norm'].notna() &
    ~df['departamento_norm'].isin(['', 'nan', 'none']) &
    ~df['municipio_norm'].isin(['', 'nan', 'none']) &
    ~df['coddpto'].isin(['', 'nan', 'None', 'none']) &
    ~df['codmpio'].isin(['', 'nan', 'None', 'none'])
].copy()

# Prioridad a años recientes
prioridad_anios = {2026: 6, 2023: 5, 2022: 4, 1988: 3, 1986: 2, 1982: 1}
valid['prioridad'] = valid['ano'].map(prioridad_anios).fillna(0).astype(int)

# Conteo por combinación nombre->código
resumen = (
    valid.groupby(
        ['departamento_norm', 'municipio_norm', 'coddpto', 'codmpio', 'ano'],
        dropna=False
    )
    .size()
    .reset_index(name='registros')
)

resumen['prioridad'] = resumen['ano'].map(prioridad_anios).fillna(0).astype(int)

# Puntaje para escoger código canónico: año más reciente primero, luego mayor frecuencia
canon = (
    resumen.sort_values(
        ['departamento_norm', 'municipio_norm', 'prioridad', 'registros'],
        ascending=[True, True, False, False]
    )
    .groupby(['departamento_norm', 'municipio_norm'], as_index=False)
    .first()
)

canon = canon.rename(columns={
    'coddpto': 'coddpto_canon',
    'codmpio': 'codmpio_canon',
    'ano': 'ano_referencia',
    'registros': 'registros_referencia'
})

# Pegar código canónico al dataset completo
df2 = df.merge(
    canon[['departamento_norm', 'municipio_norm', 'coddpto_canon', 'codmpio_canon', 'ano_referencia']],
    on=['departamento_norm', 'municipio_norm'],
    how='left'
)

# Reemplazar con código canónico donde exista
df2['coddpto_original'] = df2['coddpto']
df2['codmpio_original'] = df2['codmpio']

df2['coddpto'] = df2['coddpto_canon'].combine_first(df2['coddpto'])
df2['codmpio'] = df2['codmpio_canon'].combine_first(df2['codmpio'])

# Crear clave territorial final
df2['clave_territorial'] = df2['coddpto'].astype(str).str.strip() + '-' + df2['codmpio'].astype(str).str.strip()

# Diccionario maestro por código final para regenerar nombres uniformes
nombres_codigo = (
    df2[
        df2['coddpto'].notna() & df2['codmpio'].notna() &
        df2['departamento_norm'].notna() & df2['municipio_norm'].notna()
    ]
    .groupby(['coddpto', 'codmpio', 'departamento_norm', 'municipio_norm'])
    .size()
    .reset_index(name='registros')
)

# Priorizar nombres asociados a años recientes
tmp = df2[['coddpto', 'codmpio', 'departamento', 'municipio', 'departamento_norm', 'municipio_norm', 'ano']].copy()
tmp['prioridad'] = tmp['ano'].map(prioridad_anios).fillna(0).astype(int)

nombres_preferidos = (
    tmp.groupby(['coddpto', 'codmpio', 'departamento', 'municipio', 'departamento_norm', 'municipio_norm', 'prioridad'])
    .size()
    .reset_index(name='registros')
    .sort_values(['coddpto', 'codmpio', 'prioridad', 'registros'], ascending=[True, True, False, False])
    .groupby(['coddpto', 'codmpio'], as_index=False)
    .first()
)

nombres_preferidos = nombres_preferidos.rename(columns={
    'departamento': 'departamento_canon',
    'municipio': 'municipio_canon'
})

df2 = df2.merge(
    nombres_preferidos[['coddpto', 'codmpio', 'departamento_canon', 'municipio_canon']],
    on=['coddpto', 'codmpio'],
    how='left'
)

# Uniformar nombres según código final
df2['departamento'] = df2['departamento_canon'].combine_first(df2['departamento'])
df2['municipio'] = df2['municipio_canon'].combine_first(df2['municipio'])

# Auditoría: nombre->código y código->nombre después del ajuste
audit_nombre = (
    df2.groupby(['departamento', 'municipio'])
    .agg(
        coddpto_unicos=('coddpto', 'nunique'),
        codmpio_unicos=('codmpio', 'nunique'),
        registros=('municipio', 'size')
    )
    .reset_index()
)

audit_nombre_conf = audit_nombre[
    (audit_nombre['coddpto_unicos'] > 1) | (audit_nombre['codmpio_unicos'] > 1)
].sort_values(['departamento', 'municipio'])

audit_codigo = (
    df2.groupby(['coddpto', 'codmpio'])
    .agg(
        departamentos_unicos=('departamento', 'nunique'),
        municipios_unicos=('municipio', 'nunique'),
        registros=('municipio', 'size')
    )
    .reset_index()
)

audit_codigo_conf = audit_codigo[
    (audit_codigo['departamentos_unicos'] > 1) | (audit_codigo['municipios_unicos'] > 1)
].sort_values(['coddpto', 'codmpio'])

# Trazabilidad de cambios
trazabilidad = df2[
    (df2['coddpto_original'] != df2['coddpto']) |
    (df2['codmpio_original'] != df2['codmpio'])
].copy()

# Exportables
canon.to_csv('output/diccionario_codigos_canonicos.csv', index=False)
trazabilidad.to_csv('output/trazabilidad_cambios_codigos.csv', index=False)
audit_nombre_conf.to_csv('output/auditoria_nombre_a_codigo_postajuste.csv', index=False)
audit_codigo_conf.to_csv('output/auditoria_codigo_a_nombre_postajuste.csv', index=False)
df2.to_csv('output/dataset_homologado.csv', index=False)

In [80]:
df2.head()

,ano,corporacion,coddpto,departamento,codmpio,municipio,votos,candidato,partido,clave_territorial,departamento_norm,municipio_norm,coddpto_canon,codmpio_canon,ano_referencia,coddpto_original,codmpio_original,departamento_canon,municipio_canon
0,1982,camara,11,cauca,1,popayan,1411,lista,nuevo liberalismo,11-1,cauca,popayan,11,1,2026,19,19001,cauca,popayan
1,1982,camara,11,cauca,1,popayan,0,omar henry velasco ramirez,nuevo liberalismo,11-1,cauca,popayan,11,1,2026,19,19001,cauca,popayan
2,1982,camara,11,cauca,4,almaguer,5,lista,nuevo liberalismo,11-4,cauca,almaguer,11,4,2026,19,19022,cauca,almaguer
3,1982,camara,11,cauca,4,almaguer,0,omar henry velasco ramirez,nuevo liberalismo,11-4,cauca,almaguer,11,4,2026,19,19022,cauca,almaguer
4,1982,camara,11,cauca,5,argelia,108,lista,nuevo liberalismo,11-5,cauca,argelia,11,5,2026,19,19050,cauca,argelia

In [83]:
df2.columns

Index(['ano', 'corporacion', 'coddpto', 'departamento', 'codmpio', 'municipio',
       'votos', 'candidato', 'partido', 'clave_territorial',
       'departamento_norm', 'municipio_norm', 'coddpto_canon', 'codmpio_canon',
       'ano_referencia', 'coddpto_original', 'codmpio_original',
       'departamento_canon', 'municipio_canon'],
      dtype='object')

In [ ]:
df2.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1092364 entries, 0 to 1092363
Data columns (total 19 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   ano                 1092364 non-null  int64
 1   corporacion         1092364 non-null  object
 2   coddpto             1092364 non-null  object
 3   departamento        1092364 non-null  object
 4   codmpio             1092364 non-null  object
 5   municipio           1092364 non-null  object
 6   votos               1092364 non-null  int64
 7   candidato           1092364 non-null  object
 8   partido             1092364 non-null  object
 9   clave_territorial   1092364 non-null  object
 10  departamento_norm   1092364 non-null  object
 11  municipio_norm      1092364 non-null  object
 12  coddpto_canon       1092364 non-null  object
 13  codmpio_canon       1092364 non-null  object
 14  ano_referencia      1092364 non-null  int64
 15  coddpto_original    1092364 non-null  object
 16  codmpio_original    1092364 non-null  object
 17  departamento_canon  1092364 non-null  object
 18  municipio_canon     1092364 non-null  object
dtypes: int64(3), object(16)
memory usage: 158.3+ MB

In [84]:
cols_finales = [
    'ano', 'corporacion', 'coddpto', 'departamento',
    'codmpio', 'municipio', 'votos', 'candidato',
    'partido', 'clave_territorial', 'coddpto_canon', 'codmpio_canon'
]

df_final = df2[cols_finales].copy()
df_final.to_parquet('output/dataset_final.parquet', index=False)

In [86]:
df_final.to_csv('output/dataset_final.csv', index=False, encoding='utf-8-sig')